### ISSUE TITLE
pdepend bump to 2.13.0

### ISSUE THREAD

**Issue by d-paniutycz** [phpmd/phpmd#1002]
## Description
Could I ask for a new phpmd release with a new version of [pdepend 2.13.0](https://github.com/pdepend/pdepend/releases/tag/2.13.0) that fixes the bug: Unexpected Token with double class modifiers https://github.com/pdepend/pdepend/pull/642? I ask on behalf of phive and **phar** users. Thank you!

**Comment by AJenbo** [comment]
if you install via composer you can simply run `composer update pdepend/pdepend -w` as 2.13.0 is in the compatible range

**Comment by vladdnepr** [comment]
Yeah, I wait too. I want to receive https://github.com/phpmd/phpmd/issues/994

**Comment by vladdnepr** [comment]
Hmmm. It would be nice to make a new version

**Comment by ravage84** [comment]
@vladdnepr patience, please!

We have some other improvements that we want to get into the next release.
