### ISSUE TITLE
Add rulename to violation

### ISSUE THREAD

**Issue by tebeso** [phpmd/phpmd#1003]
It would be good to immediately see which rule has been violated (like with PHPCS). If i want to use @SuppressWarnings, i usually have to find out, what is the rules name. With PHPCS, i always get that in the report (and also in PhpStorm)

**Comment by tvbeek** [comment]
Hello @tebeso how do you mean that?

If I run PHPMD I see the rule name, example:  
![image](https://github.com/phpmd/phpmd/assets/2026498/2e1fde4a-2e00-4a0b-8c41-3a352d9d2af4)

BooleanArgumentFlag, CyclomaticComplexity, StaticAccess and ElseExpression are all the rules that you can Surpress if wanted.

I think that I don't understand your question or it is already there 😃

**Comment by AJenbo** [comment]
This could be down to a deficiency in the way PHPStorm has intergrated it

**Comment by tvbeek** [comment]
I think we need to know how the result is collected / parsed before we know what need to be added to give the additional support for PHPStorm.

**Comment by kylekatarnls** [comment]
I suspect this issue was issue for a version before rule name was added.

Anyway it's not actionable as is, so I close it, another one specifying the version the code used, current output and expected output would be evaluated if created.
