### ISSUE TITLE
LawOfDemeter - unable to set trustRatio

### ISSUE THREAD

**Issue by dbavery** [phpmd/phpmd#1027]
- PHPMD version: v6.48.0
- Installation type: https://megalinter.io/6.22.2/descriptors/java_pmd on GitLab & Intellij PMD plugin MacOS X
- Linux & MacOSX IntelliJ plugin

### Current Behavior
In our attempts to set the trust radios for the law of demeter we get a parse failure on our file:

> SEVERE: Cannot load ruleset custom_java-pmd-ruleset.xml: Cannot set non-existent property 'trustRadius' on Rule LawOfDemeter

The contents of this file are:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns="http://pmd.sourceforge.net/ruleset/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Default ruleset used by the CodeClimate Engine for Salesforce.com Java" xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">

    <description>Default RuleSet for MegaLinter</description>

    <!-- IGNORE FILES -->
    <exclude-pattern>.*/java-domainbuilder/*.*</exclude-pattern>
    <exclude-pattern>.*/app-setup/*.*</exclude-pattern>
    <exclude-pattern>.*/fflib_*.*</exclude-pattern>
    <exclude-pattern>.*/json2java/*.*</exclude-pattern>

    <!-- https://docs.pmd-code.org/pmd-doc-7.0.0-rc3/pmd_rules_java_design.html#signaturedeclarethrowsexception -->

    <!-- STANDARD RULES -->
    <rule ref="category/java/design.xml">
        <!-- unable to override the default trustRadius of 1 in intellij -->
        <exclude name="LawOfDemeter" />
    </rule>

    <rule ref="category/java/design.xml/LawOfDemeter">
        <properties>
            <property name="trustRadius" value="3" />
        </properties>
    </rule>

</ruleset>
```

We expect to be able to customize the trustRadios based on:
*  documentation: https://pmd.github.io/pmd/pmd_rules_java_design.html#lawofdemeter
*  code: https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java#L81
* test cases: https://github.com/pmd/pmd/blob/master/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/LawOfDemeter.xml#L439

I suspect we just missed the property definition in design.xml: https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/category/java/design.xml#L938 but I am not really sure.

### Expected Behavior
Explain the result that you expected.

I would expect to be able to exclude the rule from the design and then include it below with the trust radius overridden as illustrated above.

### Steps To Reproduce:
Explain **all** the steps you did to create this bug so we can reproduce it.

Try to run the above ruleset - for us we get parse errors when running via megalinter in gitlab, or via intellij PMD plugin on MAC OS X.

**Comment by kylekatarnls** [comment]
Hello,

PHPMD v6.48.0 does not exist. Latest version of PHPMD is 2.13.0 and here are all the rules available for design rule set:

https://github.com/phpmd/phpmd/tree/master/src/main/php/PHPMD/Rule/Design

PHPMD is a PHP-specific mess detector, if you're looking for PMD, please fill an issue here:

https://github.com/pmd/pmd
