### ISSUE TITLE
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /iims/vendor/phpmd/phpmd/src/main/php/PHPMD/Renderer/HTMLRenderer.php on line 490

### ISSUE THREAD

**Issue by jamesRUS52** [phpmd/phpmd#1034]
- PHPMD version: 2.13.0
- PHP Version: 8.2
- Installation type:  composer
- Operating System / Distribution & Version: Fedora 38

### Current Behavior
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /iims/vendor/phpmd/phpmd/src/main/php/PHPMD/Renderer/HTMLRenderer.php on line 490

### Expected Behavior
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /iims/vendor/phpmd/phpmd/src/main/php/PHPMD/Renderer/HTMLRenderer.php on line 490

### Steps To Reproduce:
Generate report in HTML format

**Comment by kylekatarnls** [comment]
It's already fixed and will be released in the next version:
https://github.com/phpmd/phpmd/commit/d9435b72dab165d8350eb33759f06b357fd25fd3
