### ISSUE TITLE
Using the `parent` keyword in a trait causes problems

### ISSUE THREAD

**Issue by superdweebie** [phpmd/phpmd#108]
I get the following two errors from phpmd:

`The parser has reached an invalid state...`
`The keyword "parent" was used as a type hint but the class X does not declare a parent`

Neither of these make a lot of sense. The parser shouldn't reach invalid state on what is valid code. And, the keyword parent is not being used as a type hint.

**Comment by grogy** [comment]
This problem is fixed. If you install actual version (from master branch), is all OK. (see https://github.com/pdepend/pdepend/issues/128)

You can close this ticket.

**Comment by superdweebie** [comment]
Ta
