### ISSUE TITLE
Fluent interface not supported

### ISSUE THREAD

**Issue by munnik** [phpmd/phpmd#110]
If I have a piece of code which calls some private methods using a fluent interface like this:

$this
    ->doSomething()
    ->doSomethingElse()
    ->doAnotherThing();

then PHPMD reports these methods as UnusedPrivateMethodes.

**Comment by sas05** [comment]
I agreed. 3 level chained method not supported. it is a old post but no response yet.

**Comment by eeree** [comment]
@ravage84 to be closed (https://github.com/phpmd/phpmd/issues/475)

**Comment by ravage84** [comment]
Thanks, just noticed. Closing.
