### ISSUE TITLE
Support PHPUnit dataprovider (suppress UnusedPrivateMethod)

### ISSUE THREAD

**Issue by amenk** [phpmd/phpmd#1200]
## Description

The PHPunit code

```php
     * @dataProvider languageCombinationsProvider
     */
    public function testPostLanguages(string $country, ?string $region, string $language): void
    {
       ...
    }

    private function languageCombinationsProvider(): array
    {
...
```

triggers `UnusedPrivateMethod`, probably because PHPmd does not know about the `@dataProvider` annotation.

Can this be added to avoid such an error?
Would it be in scope to support such special cases of a 3rd party framework like PHPunit?

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [ ] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by amenk** [comment]
my mistake. DataProvider should be public as I learned here:

https://github.com/phpstan/phpstan/issues/11629#issuecomment-2330844603

sorry for the noise.

**Comment by kylekatarnls** [comment]
And they should also be static.
