### ISSUE TITLE
@package_version@ not replaced as release version in phar

### ISSUE THREAD

**Issue by glensc** [phpmd/phpmd#1213]
- PHPMD version: 2.15.0
- PHP Version: Irrelevant
- Installation type: phar file
- Operating System / Distribution & Version: Irrelevant

### Current Behavior

Brew package downloaded from https://github.com/phpmd/phpmd/releases/download/2.15.0/phpmd.phar doesn't display version

```
$ phpmd /etc/passwd xml unusedcode
<?xml version="1.0" encoding="UTF-8" ?>
<pmd version="@package_version@" tool="phpmd" timestamp="2024-10-18T09:21:40+00:00">
</pmd>
```

Formula definition:
- https://github.com/Homebrew/homebrew-core/blob/376641e86202b509a04a2dab0a0bda7d695babd2/Formula/p/phpmd.rb

### Expected Behavior

Display `2.15.0`

### Steps To Reproduce:
1. `wget https://github.com/phpmd/phpmd/releases/download/2.15.0/phpmd.phar`
2. `php phpmd.phar /etc/passwd xml unusedcode`

`@package_version@` was fixed before:
- https://github.com/phpmd/phpmd/issues/130

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by glensc** [comment]
Update, I had a bogus copy in `$PATH`, but the correct phar still IMHO doesn't display the release version:

```
❯ /opt/homebrew/opt/php@8.0/bin/php phpmd.phar /etc/passwd xml unusedcode
<?xml version="1.0" encoding="UTF-8" ?>
<pmd version="2.15.0snapshot202312110823" tool="phpmd" timestamp="2024-10-18T09:22:21+00:00">
</pmd>
```

**Comment by AJenbo** [comment]
I'm not seeing anything strictly wrong here, also the build process is changed for 3.x to where this isn't the case either.
