### ISSUE TITLE
Permission error in test suite

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#13]
PHPMD's test suite uses a global file in the */tmp* directory. This results in a failing test when we run the test suite with different users on *nix system.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/9626017']

**Comment by ravage84** [comment]
The Pivotal Tracker states that this was fixed in: https://github.com/manuelpichler/phpmd/commit/b385f15
Going to close.
@manuelpichler  please reopen if you think this is still an issue.
