### ISSUE TITLE
[Bug] Traits with parent:: calls fails

### ISSUE THREAD

**Issue by lsv** [phpmd/phpmd#133]
````
trait Foo {
     public function foobar() { parent::doStuff(); }
}

class Bar {
  use Foo;
  public function doStuff() { echo 'Stuff'; }
}

$o = new Bar;
echo $o->foobar();
````

The code is fully valid - But get this error from phpmd

The parser has reached an invalid state near line "xxx" in file "Traits/Foo.php". Please check the following conditions: The keyword "parent" was used as type hint but the class "Foo" does not declare a parent.

**Comment by grogy** [comment]
This problem is fixed. If you install actual version (from master branch), is all OK. (see https://github.com/pdepend/pdepend/issues/128)

You can close this ticket.
