### ISSUE TITLE
Conflict for abstract methods in traits

### ISSUE THREAD

**Issue by hgiesenow** [phpmd/phpmd#153]
This example will lead to an error in phpmd, that leads to aborting the whole phpmd check.

```php
trait MyTrait {
  protected function foo() {
    $this->bar();
  }
  abstract public function bar();
}

class MyClass extends AbstractClass {
  use MyTrait;
}

class AbstractClass {
  public function bar() {
    echo 'bar';
  }
}
```

Leads to

```
phpmd:
     [exec] Trait method bar has not been applied, because there are collisions with other trait methods on MyClass.
     [exec] Result: 1
```

Edit: A Quickfix would be 

```
use MyTrait {
  AbstractClass::bar insteadof MyTrait;
}
```

But this leads to much more unreadable code, especially when using more traits (and also throws phpcs error "contant not uppercase, but that's another topic)

Edit 2: The Quickfix only works for traits, not for classes, so no way to pass the phpmd with this.

**Comment by kylekatarnls** [comment]
Indeed this issue is the same as https://github.com/pdepend/pdepend/issues/154 and has been fixed in PDepend.
