### ISSUE TITLE
LongVariable rule should not apply on private properties

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#16]
The LongVariable rule should ony apply on *public* and *protected* properties, because *public* properties are part of the external api and *protected* properties are part of the internal api. But *private* properties have an internal purpose and so they should be descriptive.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/10096717']

**Comment by ravage84** [comment]
Fixed in f063bc9

**Comment by adamcameron** [comment]
This change is a bit wrong-headed, I think? Mess detector rules are about humans reading code, not about APIs. When reading code, it's about the code in front of the person, not what purpose the computer puts the code to.
