### ISSUE TITLE
Implement rule for CBO metric

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#17]
Implement a new rule that checks the CBO metric which will be available with PHP_Depend 0.10.2.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/10474987']

**Comment by ravage84** [comment]
Seems to be implemented already: https://github.com/phpmd/phpmd/blob/f93ced10081aedd69163966af7ca8eae0e1beac2/src/main/php/PHPMD/Rule/Design/CouplingBetweenObjects.php

**Comment by manuelpichler** [comment]
lol
