### ISSUE TITLE
Order by directory

### ISSUE THREAD

**Issue by flip111** [phpmd/phpmd#171]
For the unusedcode filterrule it would be nice if the output was ordered by directory rather then alphabetically.

```
Afile
CanotherFile
B/folder
```

instead of

```
Afile
B/folder
CanotherFile
```

**Comment by ravage84** [comment]
I could see that as a CLI option or rule set property, but it seems to be rather an edge use case.

**Comment by kylekatarnls** [comment]
It's very old and as our to-do list is pretty big, we can't handle this. If someone want to do a PR for this, we would reconsider.
