### ISSUE TITLE
Detect unnecessary public methods.

### ISSUE THREAD

**Issue by flip111** [phpmd/phpmd#174]
It would be nice if PHPMD could detect methods that are declared public, but are never called from outside of the class (or it's children). And advise to make it either private or protected.

**Comment by sebastienbarre** [comment]
Just curious about this one too. I agree with @flip111 I think this would be very valuable for us working on large, self-contained applications, while transitioning to a full code-coverage via tests.

**Comment by ravage84** [comment]
Closing as I don't see this being done in a proper way. With static analysis, which is what PHPMD is, you have quite limited possibilities. Also PHP being a weekly typed language with its dynamic calling capabilities being used quite often, doesn't make it easier.
I'd rather implement this in a runtime analysis tool. Such as NewRelic.

If any of you guys are still interested in implementing this. I'm open to a PR.
