### ISSUE TITLE
Support POSIX file globbing, and STDIN.

### ISSUE THREAD

**Issue by kid-icarus** [phpmd/phpmd#185]
Could someone explain to me the logic behind having to specify a path with --suffixes and --exclude options instead of being able to stream in files, use STDIN, or use file globs?

I'm trying to write a phpmd plugin for gulp.js and this is an extreme hindrance for me.

**Comment by ravage84** [comment]
@kid-icarus feel free to create a PR which implements this.

**Comment by kid-icarus** [comment]
lol I don't use php anymore. good luck!

**Comment by withwind8** [comment]
STDIN has been implemented in the upstream.    [Support stdin #262](https://github.com/pdepend/pdepend/pull/262)
Specify '-' or 'php://stdin' as filename to use STDIN.

But it was broken now. (By [Apply the filter on files as well #231](https://github.com/pdepend/pdepend/pull/231))

Maybe I will submit a PR to fix it later.

**Comment by ravage84** [comment]
@withwind8 that would be cool 👍

**Comment by kylekatarnls** [comment]
About STDIN, you can already use it this way:

```
cat src/MyFile.php | ./src/bin/phpmd php://stdin text foo/rules.xml
````

But we could add the same short-cut `-` than in PDepend.
