### ISSUE TITLE
Add a AppVeyor build badge to the README

### ISSUE THREAD

**Issue by ravage84** [phpmd/phpmd#213]
Once, there is an AppVeyor project configured to point to this repo, we can also add a build badge in the  [README](https://github.com/phpmd/phpmd/blob/master/README.rst).

Can be found under "Badges" in the AppVeyor's project settings.

[![Build status](https://ci.appveyor.com/api/projects/status/oua8ohd7nvspix65?svg=true)](https://ci.appveyor.com/project/ravage84/phpmd)

**Comment by ravage84** [comment]
@manuelpichler have you created an AppVeyor project yet?

You merged my related PR https://github.com/phpmd/phpmd/pull/208

**Comment by manuelpichler** [comment]
@ravage84 no, I did not :-( Would you like to do this on your own and support PHPMD when I add you as a project's team member?
