### ISSUE TITLE
UnusedFormalParameter should detect use of "variable properties"

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#22]
A method with a formal parameter ($property) that is used as the name of an object (or class?) property is erroneously reported as not using that parameter.

Steps to Reproduce
---------------------------

class Foo
{
    public $value = 5;
    
    public function getValue($property) {
        return $this->$property;
    }
}

Expected Result
----------------------
no errors or warnings

Actual Result
------------------
Medium: Avoid unused parameters such as '$property'.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/14081267']

**Comment by ravage84** [comment]
Fixed in 183fbd5
