### ISSUE TITLE
Wrong detection for unused variables with compact()

### ISSUE THREAD

**Issue by Mulkave** [phpmd/phpmd#224]
I get the violation: `Avoid unused local variables such as '$whatever'` while being used in `compact('whatever')`

**Comment by zippy1981** [comment]
Here is another example of this where it happens with double quotes, but not single quotes:

https://github.com/zippy1981/phpmd_bugs/tree/compactBug

**Comment by ravage84** [comment]
Should be fixed in PHPMD 2.6.0:
![compact](https://cloud.githubusercontent.com/assets/625761/26749670/1d5f8b98-4810-11e7-87b4-73d91dedfcbb.png)
