### ISSUE TITLE
Violation-message from ExcessiveMethodLength-rule

### ISSUE THREAD

**Issue by Eternal-Infinity** [phpmd/phpmd#234]
Hi there,

I used the codesize-ruleset on my project and got a strange message for a violation from the ExcessiveMethodLength-rule: 

```
The phpmd\node\methodnode _getLayout() has 136 lines of code. Current threshold is set to 100. Avoid really long methods.
```

While all other rules give me something like 

```
The method _getLayout() has an NPath complexity of 120012. The configured NPath complexity threshold is 200.
```

It seems that the ExcessiveMethodLength-rule has some problems to display "method" and instead displays "phpmd\node\methodnode"
Or did I get something wrong?

**Comment by ravage84** [comment]
Funny enough, I don't see the difference between those two rules:

https://github.com/phpmd/phpmd/blob/2.4.3/src/main/php/PHPMD/Rule/Design/LongMethod.php#L86
https://github.com/phpmd/phpmd/blob/2.4.3/src/main/php/PHPMD/Rule/Design/NpathComplexity.php#L78

Can you re-try it with the most current version, please?

**Comment by tvbeek** [comment]
I close this issue because we didn't got any verification after a couple of years.
Feel free to reopen if this is relevant.
