### ISSUE TITLE
Output for version

### ISSUE THREAD

**Issue by Eternal-Infinity** [phpmd/phpmd#235]
Hi there,

I use the phpmd.phar I downloaded from http://static.phpmd.org/php/2.1.3/phpmd.phar.
The xml-output gives me something like this:

```
[...]
<pmd version="@project.version@" timestamp="2014-11-27T15:21:22+01:00">
[...]
```

Is there something I have to configure to make the output of the version correct?

**Comment by tvbeek** [comment]
I suspect this could be set in the build script for the PHAR file.

**Comment by kylekatarnls** [comment]
For the record, it's not replaced either using `./vendor/bin/phpmd`

**Comment by sveneld** [comment]
#743

**Comment by sveneld** [comment]
@kylekatarnls this issue can be closed
