### ISSUE TITLE
TooManyMethods and method visibility

### ISSUE THREAD

**Issue by JeroenDeDauw** [phpmd/phpmd#248]
The TooManyMethods rule applies to all methods, regardless of their visibility. Holding visibility into account seems very useful, since while 10 methods (excluding getters and setters) in itself is not necessarily an indication or SRP violation, 10 public methods definitely is. Looking at the rules class, it does not appear there is any option for this. Are there plans of adding such an option? If not, are there any objections against this being done? And if not, how would this best be implemented? As config for the existing rule or a new rule?

Related: the TooManyMethods rule is the only of which I disagree with the default value (so far). If you "extract till you drop", it's quite easy to end up with a bit over 10 methods in a single class, without violating the SRP. Something between 15 and 20 is IMO better.

**Comment by ravage84** [comment]
@JeroenDeDauw thank you for your inputs.

I agree with you, as the ``TooManyMethods`` rule currently stays, it's rarely really applicable without modifying the limit.

I would split them in two a) ``TooManyMethods`` and ``TooManyPublicMethods``. Where the ``TooManyMethods`` applies for all methods. But with a much higher default value, e.g. 20-30. As for the ``TooManyPublicMethods``, I would set the default value to something between 15-20.

Right now, as far as I know, there are no plans. Are you interested in putting up a PR?

**Comment by manuelpichler** [comment]
:+1: for the idea of two separate rules.

**Comment by ravage84** [comment]
On the other side, creating a second class could lead to redundant code in phpmd.
If that is the case, a second config setting, for example named ``maxpublicmethods``, would  be better.

**Comment by ravage84** [comment]
And your side note about getters and setters should not be overlooked, too.

Because on somewhat bigger data objects there could be quite a few fields and thus around twice as much getters and setters.
So a config setting to ignore getter and/or setter methods would be cool, for example: ``ignore-getter-setter-methods``, or  ``ignore-setter-methods`` and ``ignore-getter-methods``.

**Comment by JeroenDeDauw** [comment]
I'll try to submit a PR soon with what @ravage84 suggested:

* Modify `TooManyMethods` default limit to 25 or so
* Create `TooManyPublicMethods`

> On the other side, creating a second class could lead to redundant code in phpmd.

If it's a lot of code, then composition can probably be used no? Anyway, I'd rather think about what we want the user experience to be from the users point of view, not from what the implementation would look like.

> And your side note about getters and setters should not be overlooked, too.

Note that getters and setters are already excluded by the current rule. I'm not sure how much sense it makes to add config for this (if there is none yet, I don't recall). That is not the issue I want to tackle here though.

**Comment by ravage84** [comment]
@JeroenDeDauw  while it's true to focus on the usability for the end user of a tool, you should not forget about the [technical debt](http://en.wikipedia.org/wiki/Technical_debt).
As a user of a software you might not care much about this, but in the end the developers/maintainers of a software will have to *live* with the potential consequence(s) of each written line of code. Especially when it is a piece of a public API...

And thank you for pointing out the already implemented exclusion of getters and setters. Didn't know that and didn't check before writing. ;-)

http://phpmd.org/rules/codesize.html#toomanymethods
But that means the documentation is lacking...

**Comment by yoosefi** [comment]
Any opinions on whether `@deprecated` methods should be excluded as well?

**Comment by ravage84** [comment]
@yoosefi  Not by default. Especially since some people use the ``@deprecated`` annoation also for deprecating parameters of methods
I could see that as a rule setting, though.

**Comment by yoosefi** [comment]
Are `isFoo()` methods counted, since those should be used to get booleans?

**Comment by JeroenDeDauw** [comment]
They are not ignored by default. My pull request adds a setting that allows you to also ignore those though: https://github.com/phpmd/phpmd/pull/273/files

**Comment by yoosefi** [comment]
:+1:

**Comment by ravage84** [comment]
Closing as https://github.com/phpmd/phpmd/pull/273 was merged.
