### ISSUE TITLE
False Unused Private Method When Using Method As Callback

### ISSUE THREAD

**Issue by quantumpacket** [phpmd/phpmd#253]
When I call a private method as a callback I get:
> phpmd: Avoid unused private methods such as '...'

### Example:
This works fine, but phpmd thinks the private method is not being used.

```php
class Foo
{
    public function bar(array &$values)
    {
        array_walk($values, [$this, 'baz']);
    }

    // phpmd: Avoid unused private methods such as 'baz'
    private function baz(&$value, $key)
    {
        $value = $key;
    }
}

$arr = ['a' => '1', 'b' => '2', 'c' => '3'];
$obj = new Foo();
$obj->bar($arr);

print_r($arr);
```
**IDE:** PhpStorm 8.0.3
**phpmd:** 2.2.0 *(dev-master)*

**Comment by yoosefi** [comment]
There's really no way to check for string method names. Some callbacks are constructed using string concatenation, for example.

Is that the only place you're doing it? Could you just use a closure instead?

Try tagging the method with `@SuppressWarnings(PHPMD.UnusedPrivateMethod)`

**Comment by bkdotcom** [comment]
> There's really no way to check for string method names

how about:

`array_walk($values, $this->baz');`

still results in "Avoid unused private methods such as 'baz'"

**Comment by yoosefi** [comment]
That will try to look up `baz` as a property, which doesn't exist.

**Comment by bkdotcom** [comment]
> That will try to look up baz as a property, which doesn't exist.

d'oh.   My bad.  I had just gone from using an anonymous function as my callback and didn't realize the code hadn't been tested since converting to a method.

Seems like when, in the context of a callback, PHP should (insert magic here) fallback and check if  `$this->baz` is a method

**Comment by yoosefi** [comment]
PHP internally separates methods and properties, which is why it's not illegal to have a property and method share a name,

You can implement `__call()` to check for callable properties, but otherwise, yeah, it'd be nice but oh well.
