### ISSUE TITLE
Search for development code

### ISSUE THREAD

**Issue by snapshotpl** [phpmd/phpmd#265]
I would like to see in phpmd search for typical development functions:
* var_dump
* die
* exit
* var_export

etc.

**Comment by Eternal-Infinity** [comment]
Great idea!
:+1:

**Comment by manuelpichler** [comment]
:+1:

**Comment by ravage84** [comment]
@snapshotpl are you willing to create a PR on this?
By the way there is already a rule against the ``eval`` expresssion:
https://github.com/phpmd/phpmd/blob/2.2.1/src/main/php/PHPMD/Rule/Design/EvalExpression.php
and against ``exit``:
https://github.com/phpmd/phpmd/blob/2.2.1/src/main/php/PHPMD/Rule/Design/ExitExpression.php

**Comment by snapshotpl** [comment]
@ravage84 I don't think so

**Comment by manuelpichler** [comment]
Implemented in dfa6872
