### ISSUE TITLE
Update PEAR packages

### ISSUE THREAD

**Issue by jonathan-dh** [phpmd/phpmd#266]
Could you pls update the pear repo to include 2.2.0 pls?

Great tool btw!

Let me know if I can help to make this happen!

**Comment by manuelpichler** [comment]
Sorry but we have dropped PEAR support since 2.0 completely. Couldn't you use composer instead?

**Comment by aosmialowski** [comment]
PEAR? Any one still using it? +1 for Composer suggestion.

@manuelpichler what about providing PHAR instead as requested in #274?

**Comment by manuelpichler** [comment]
@aosmialowski see my comment at #274

**Comment by aosmialowski** [comment]
@manuelpichler thank you. I don't know why but I've missed it.

**Comment by manuelpichler** [comment]
Except someoneelse maintains the pear support of PHPMD, there will not be any 2.x version through pear.
