### ISSUE TITLE
ShortMethodName OutOfBoundsException missing backslash

### ISSUE THREAD

**Issue by tvking** [phpmd/phpmd#269]
Running the PHPMD 2.2.1 using phing ci I get the following message:
  Property "exceptions" does not exist.

This result in the pmd.xml being empty once phing has completed. 

The issue is with the file PHPMD\Rule\Naming\ShortMethodName which contains the function below. Which is missing the backslash on the OutOfBoundsException.

```
private function getExceptionsList()
    {
        try {
            $exceptions = $this->getStringProperty('exceptions');
        } catch (OutOfBoundsException $e) {
            $exceptions = '';
        }

        return explode(',', $exceptions);
    }
```

Adding the slash and running phing ci solve the problem for me.

**Comment by ravage84** [comment]
Resolved through your PR.
