### ISSUE TITLE
Link to download phpmd phar (version independent)

### ISSUE THREAD

**Issue by jdespatis** [phpmd/phpmd#274]
It's possible to download phpmd thanks to the link https://github.com/Mayflower/PHP_CodeBrowser/releases/download/1.1.1/phpcb-1.1.1.phar
but this link depends on the version

Is there some link that doesn't depend on the version?

Other tools provides such links like https://phar.phpunit.de/phpunit.phar, http://static.pdepend.org/php/latest/pdepend.phar, etc.

A fix link is useful for automatic downloading in script

**Comment by manuelpichler** [comment]
PHPMD has the same latest version:

http://static.phpmd.org/php/latest/phpmd.phar

Isn't that mentioned on the website somewhere?

**Comment by aosmialowski** [comment]
I can't find it. What about adding it under Download menu as a link saying "Latest release as a PHAR archive"?

**Comment by jdespatis** [comment]
Thanks for the link @manuelpichler !

I haven't found it indeed. The only section that speaks about the PHAR is on GitHub (the `README.rst`') that only forwards to http://phpmd.org/download/index.html

And on the download page of phpmd, there's no section speaking about PHAR. It would help to add a section there I think

**Comment by jdespatis** [comment]
Thanks @manuelpichler !
