### ISSUE TITLE
System wide installation via composer. 

### ISSUE THREAD

**Issue by ronlinet** [phpmd/phpmd#283]
I have installed the PHPMD 2.2.2 via composer  as superuser in 
```bash
/root/.comopser/phpmd
``` 
and I can see the executable link in 
```bash
/root/.comopser/bin/phpmd
``` 
I can execute the command at system wide level from any directory as far as I am logged as root superuser. 
The phpmd command will become inaccessible as soon as I loging as any other user. 
Creating symbolic link doesn't work either 

```bash
ln -s /root/.composer/vendor/phpmd/phpmd/src/bin/phpmd /usr/bin/phpmd
``` 
and I am even getting permission denied if I try to execute the link directly : 

```bash
/usr/bin/phpmd
```
The permission denied is still there even after having changed executable to 777 :  

```bash
chmod 777 /root/.composer/vendor/phpmd/phpmd/src/bin/phpmd 
```

What is the best installation approach to install the phpmd through the composer at system wide level? 

OS => Ubuntu 12.04

**Comment by ravage84** [comment]
@ronlinet I think your question is better suited at http://stackoverflow.com generally or http://stackoverflow.com/questions/tagged/phpmd specifically as your problem is more about your environment and less about phpmd.
