### ISSUE TITLE
incompatibe with zend extension uopz.overloads=1

### ISSUE THREAD

**Issue by Vinai** [phpmd/phpmd#284]
If the zend extension [uopz](https://github.com/krakjoe/uopz/) is installed and `uopz.overloads = 1` is configured, phpmd.phar breaks:
```
[vinai@Sayyadina:/usr/local/etc/php/5.6/conf.d on master]
% cat ext-uopz.ini
[uopz]
zend_extension="/usr/local/opt/php56-uopz/uopz.so"
uopz.overloads = 1
[vinai@Sayyadina:/usr/local/etc/php/5.6/conf.d on master]
% php --version
PHP 5.6.9 (cli) (built: May 15 2015 09:36:14)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with uopz v2.0.7, Copyright (c) 2014, by Joe Watkins <krakjoe@php.net>
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans
[vinai@Sayyadina:/usr/local/etc/php/5.6/conf.d on master]
% phpmd --version                                                                                                                              127 ↵
PHPMD 2.2.2
PHP Fatal error:  Invalid opcode 65/4/8. in /usr/local/bin/phpmd on line 0
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpmd:0

Fatal error: Invalid opcode 65/4/8. in /usr/local/bin/phpmd on line 0

Call Stack:
    0.0003    2074240   1. {main}() /usr/local/bin/phpmd:0
```

Once `uopz.overloads` is not set (or the uopz extension is removed completely) phpmd works fine.
The same behavior can also be found in php 5.5.25.

Do you have any idea what in phpmd might cause this issue or how to work around it? I would really like to use both phpmd and uopz.overload in CI.

Since I don't know if this or phpmd is a better repository to report the issue I've cross posted here: https://github.com/krakjoe/uopz/issues/19

**Comment by ravage84** [comment]
@Vinai  Thanks for reporting this.
Since I don't know  of any such problem and a [Google](https://www.google.ch/search?q=Invalid+opcode+%22phpmd%22&gws_rd=ssl#q=%22Invalid+opcode%22+%22pdepend%22) [search](https://www.google.ch/search?q=Invalid+opcode+%22phpmd%22&gws_rd=ssl#q=%22Invalid+opcode%22+%22phpmd%22) does not reveal anything related, I can only pressume that the problem lies within the uopz extension.

**Comment by Vinai** [comment]
Thanks for the reply!
I didn't find anything related on google either. That is part of the reason why I decided to add this issue, so that someone who has a similar issue might find it.
Probably nothing is found because the uopz extension is not used widely as far as I can tell. However, it is really neat. I'm using it to overload the PHP `exit` function for testing some legacy code during CI.

**Comment by diyism** [comment]
It seems uopz conflicts with php 5.4.42 when your php code contains "exit()".
