### ISSUE TITLE
Allow PHP_Depend configuration option from command line

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#29]
The configuration option of PHP_Depend allows the ability to customize the location of the cache file. Without this ability, PDepend, and therefore PHPMD, try to write the cache file based on $HOME. OK for local work, but not in a Tomcat-based Jenkins deployment.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/22407623']

**Comment by guiyomh** [comment]
+1

**Comment by manuelpichler** [comment]
If a file named ```pdepend.xml``` or ```pdepend.xml.dist``` exists in the current working directory where you run phpmd, then you can configure [pdepend](http://pdepend.org/documentation/handbook/configuration.html) as you like.

**Comment by ravage84** [comment]
@manuelpichler may be we need to cover this better in the documentation. People seem to not be to be aware of this.

I guess a link from http://phpmd.org/documentation/index.html to http://pdepend.org/documentation/handbook/configuration.html with a short explanation should suffice.

**Comment by manuelpichler** [comment]
Good hint @ravage84

**Comment by donaldducky** [comment]
@manuelpichler is there a way to specify the pdepend configuration to use via phpmd?

```
$ pdepend --configuration=my.config.xml
```

We have a need to run phpmd against several different folders, in parallel, so they need different cachedirs for pdepend...otherwise the cache gets all whack.
