### ISSUE TITLE
force unusedcode for "global" variables

### ISSUE THREAD

**Issue by SailorMax** [phpmd/phpmd#298]
Can you add parameter for "unusedcode" or some kind of markup per file (/* phpmd: unusedcode=+global_vars */) to detect unused variables in global name space?

My engine has directory, from where it take files from system function => all that files are source of function, which has include() => we can detect unused variables inside that files.

Sample:
file:
``` php
<? /* phpmd: unusedcode=+global_vars */
 $foo = 12;
?>
```

Exp: "Avoid unused local variables such as '$foo'."
Act: nothing

**Comment by ravage84** [comment]
Duplicate of #294
