### ISSUE TITLE
ignore unused named parameter for UnusedLocalVariable

### ISSUE THREAD

**Issue by ivoba** [phpmd/phpmd#299]
I often use "named parameters" in constructors or methods, this makes reading more easy:

     return new ThisClass(
        $id = 1,
        $type = 'mock',
        $user,
        $product,
        $item = $otherItem
     );

And i would like to suppress these messages, just as for *allow-unused-foreach-variables*:

    Avoid unused local variables such as '$id'.

**Comment by ravage84** [comment]
Hi @ivoba

Personally I disagree with your statement about increased readability. Or better said I would simply instantiate the variables just before the object instantiation and the PHPMD violations are gone plus the readability is still maintained. 

But why don't you create a PR to implement this analog to https://github.com/phpmd/phpmd/pull/198 ?
If it's a simple change we can consider to  include it.

Closing and waiting for a PR to discuss :smirk_cat:
