### ISSUE TITLE
Use new travis infrastructure.

### ISSUE THREAD

**Issue by BernardoSilva** [phpmd/phpmd#305]
Start using new Travis container based infrastructure.

http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure

**Comment by ravage84** [comment]
Thanks @BernardoSilva for bringing this up.
But at the moment I don't feel we need to push for it as I see no compelling reason to do so.

Also the feature is quite new and I prefer stability over feature craze.
http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

> But this stack is still in its early stages. We're improving the build environment just as we improve the infrastructure around it over the coming weeks. This also means that the environment may change in unexpected ways along the way. 

Once there is a real use for us to use Travis' new container-based infrastructure, we can rediscuss this.

**Comment by BernardoSilva** [comment]
Fair enough :+1: 
I also prefer stability.
Have been using it for a while and looks really good until now.
