### ISSUE TITLE
LICENSE issue

### ISSUE THREAD

**Issue by remicollet** [phpmd/phpmd#310]
You are providing a phar which violate the bundled library license.

  * Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in
    the documentation and/or other materials provided with the
    distribution.

So, at least, you need to add each component LICENSE file in the phar archive.

Doing downstream job, being hit by downstream issue ;)

**Comment by remicollet** [comment]
Notice that latest pdepend.phar seems ok, so I think problem will be solved generating a new archive (as IIRC latest composer manage this)

**Comment by manuelpichler** [comment]
This is fixed in newer releases-
