### ISSUE TITLE
Use PHPMD 2.3.* with Symfony 2.3.*

### ISSUE THREAD

**Issue by mi-schi** [phpmd/phpmd#312]
Hi

Unfortunately it is impossible to use PHPMD 2.3.* with Symfony 2.3.*. You require symfony 2.4 components in your composer.json. Can you replace it with @stable tags?

**Comment by ravage84** [comment]
I would prefer ``^2.3.0``, if possible. Right now I'm not sure though, why we depend on 2.4...

**Comment by ravage84** [comment]
I removed all Symfony dependencies in phpmd, now my PR for pdepend  must be merged, too.
See https://github.com/pdepend/pdepend/pull/223

Closing as this is no longer a phpmd related problem.
