### ISSUE TITLE
allow-underscore-test option now showing on site docs

### ISSUE THREAD

**Issue by JeroenDeDauw** [phpmd/phpmd#314]
The `allow-underscore-test` option that was added to `CamelCasePropertyName` in 2.3.0 is not showing up on the site. It is however documented in controversial.xml, so I'm assuming the documentation generation thing was not run.

**Comment by ravage84** [comment]
> I'm assuming the documentation generation thing was not run.

Is there one? 😮

**Comment by JeroenDeDauw** [comment]
That is my guess, idk how you build you site

**Comment by tvbeek** [comment]
This is now showed correctly: https://phpmd.org/rules/controversial.html so I close this issue.
