### ISSUE TITLE
Inspection: missing import

### ISSUE THREAD

**Issue by mindplay-dk** [phpmd/phpmd#321]
We have a code standard that says all classes must be imported - for example, the following is invalid:

``` php
namespace foo;

class Bar {
    public function run() {
        throw new \RuntimeException();
    }
}
```

It should be:

``` php
namespace foo;

use RuntimeException;

class Bar {
    public function run() {
        throw new RuntimeException();
    }
}
```

In other words, fully-qualified type-references are disallowed - everything must be imported.

Why? Because we want a list of `use`-clauses at the top of every file listing any dependencies of that file on types outside of it's own namespace. (our namespaces map to domains.)

Would you accept a PR for this feature?

How should it be classified? (what category? "controversial" maybe?)

Would you demand an "auto fix" for this rule, or is that optional?

**Comment by ravage84** [comment]
It sounds interesting, at least.
Have you checked, if phpcs already provides a sniff for this?

It comes down to the question, whether this issue is a code mess or a code style problem.
I tend to call it a code mess.

As for the category, the clean code category seems to be most approriate category for this one:
http://phpmd.org/rules/cleancode.html

I would call the rule rule ``MissingImport``.

At the moment, there is no auto-correction built-in.

What do you think @manuelpichler ?

**Comment by mindplay-dk** [comment]
> Have you checked, if phpcs already provides a sniff for this?

I recently configured rule sets for both tools from the ground up, pretty sure it doesn't have that - I think Storm has it, but I'm increasingly leaning away from Storm because we can't run their inspections on our CI server...

**Comment by ravage84** [comment]
@mindplay-dk  are you still interested in creating a PR for this? I would appreciate it. :smile_cat:

**Comment by mindplay-dk** [comment]
@ravage84 I'm interested, but I don't really have the time - too many other projects...

**Comment by ravage84** [comment]
Easy, take your time. It's not going away, I guess :smirk_cat:

**Comment by DmitryNaum** [comment]
Hi, i wanna try implement this feature.

**Comment by kylekatarnls** [comment]
Hi @DmitryNaum, we did not have a clear assignee for this so I assigned you. Ask me if you need help, to clone, send PR or anything.

**Comment by ravage84** [comment]
Closed through merging #636

**Comment by luckyraul** [comment]
These rule in default checks is nonsense.

**Comment by kylekatarnls** [comment]
Nope, add `use Exception;` at the top of the file if you use it is a best practice. Using `\Exception` is a mess. If you have an other opinion, you can disable the rule but there is no doubt it has its place in default configuration.

**Comment by MatheusNaldi** [comment]
This only works when it has a `new` word before the class, the examples below doesn't work:

```PHP
try {
    // something...
} catch (\Exception $e) {
    // something...
}
```

```PHP
$format = \DateTime::W3C;
```
