### ISSUE TITLE
[Proposal] duplicated array indexes rule

### ISSUE THREAD

**Issue by wandersonwhcr** [phpmd/phpmd#322]
Hello!

Yesterday I was developing my application and I had some problems with a `git merge` in an `array` definition. Example:

`array` configuration before `git merge`:

``` php
<?php
return array(
    // ...
    'default' => array(),
    // ...
);
```

`array` configuration after `git merge --no-ff issue-1`:

``` php
<?php
return array(
    'config' => array(
        'a' => true,
    ),
    // ...
    'default' => array(),
   // ...
);
```

`array` configuration after `git merge --no-ff issue-2`:

``` php
<?php
return array(
    'config' => array(
        'a' => true,
    ),
    // ...
    'default' => array(),
    // ...
    'config' => array(
        'b' => true,
    ),
);
```

Capturing  configuration, PHP defined an `array` with this structure:

``` php
$config = array(
    'config' => array(
        'b' => true,
    ),
    'default' => array(),
);
```

Boom. Configuration for `$config['config']['a']` was undefined. So, after 1 hour, I found the problem (hehe), duplication of indexes in `array` definition.

Can you create a rule for this problem, verifying duplicate indexes?

``` php
<?php
return array(
    'config' => array(
        'a' => true,
        'b' => true,
    ),
    // ...
    'default' => array(),
    // ...
);
```

PS: If we have duplicated subindexes, verify too?

PS2: I did the same question at `php-cs-fixer` project FriendsOfPHP/PHP-CS-Fixer#1469.

**Comment by ravage84** [comment]
Didn't you review the changes/merge?
Also a good IDE, such as PhpSotrm, warns you about this built-in.

Nontheless, if you would create a PR with a rule covering this issue, I would consider it merging it.

And, yes this rule should warn about any duplicated array keys in any sub-level.

**Comment by wandersonwhcr** [comment]
Yes, I did a review, but `array` had some 50+ indexes with 200+ lines and I'm human being :smile:

Thank you!

**Comment by eeree** [comment]
@ravage84 @wandersonwhcr 
It's already implemented in https://github.com/phpmd/phpmd/pull/484

**Comment by ravage84** [comment]
Oh thanks. Forgot to close.
