### ISSUE TITLE
[Proposal] weird foreach behavior

### ISSUE THREAD

**Issue by wandersonwhcr** [phpmd/phpmd#323]
My friend just found a "weird behavior" in PHP, but it's acceptable.

``` php
$one = array('a');
$two = array('b');

foreach ($one as &$value) {
    $value = strtoupper($value);
}

foreach ($two as &$value) {
    $value = strtoupper($value);
}

foreach ($one as $value) {
}

var_dump($one, $two);
```

Outputs:

```
array(1) {
  [0]=>
  string(1) "A"
}
array(1) {
  [0]=>
  &string(1) "A"
}
```

Wow!

But, if we unroll all foreach'es:

```
<?php
$one = array('a');
$two = array('b');

$value = &$one[0];
$value = strtoupper($value);

$value = &$two[0];
$value = strtoupper($value);

$value = $one[0];

var_dump($one, $two);
```

... everything makes sense. `$value` points to last position of array `$two`. But it's weird hehe.

So, can we create a rule to check this?

**Comment by ravage84** [comment]
@wandersonwhcr how would/should this check work?
What should it look for?

Seems to be quite an edge case...

**Comment by wandersonwhcr** [comment]
Too old issue.
