### ISSUE TITLE
Unexpected token when using group use declarations

### ISSUE THREAD

**Issue by radmen** [phpmd/phpmd#327]
When group use statements are used PHPMD returns error:

```
/var/www/html/src/WebPlugin/Api/Jwt/TokenFactory.php    -   Unexpected token: {, line: 5, col: 18, file: /var/www/html/src/WebPlugin/Api/Jwt/TokenFactory.php
```

Example code:

``` php
<?php

namespace WebPlugin\Api\Jwt;

use Lcobucci\JWT\{
    Builder,
    Token,
    Parser,
    Signer\Hmac\Sha256
};
use Illuminate\Http\Request;
```

PHPMD version `2.3.2`

**Comment by ravage84** [comment]
I assume the problem lies in pdepend

**Comment by JeroenDeDauw** [comment]
This is a duplicate of https://github.com/phpmd/phpmd/issues/279

**Comment by ravage84** [comment]
@JeroenDeDauw it's related but not a full duplicate, that's why I keep it open. Thanks for noting.

**Comment by JeroenDeDauw** [comment]
Apparently I misread this issue. Indeed not a duplicate at all

**Comment by torkiljohnsen** [comment]
One year later, this is still an issue in PHPMD. Are there any related pdepend issue for this?

**Comment by ravage84** [comment]
@torkiljohnsen haven't found any. Pleas open one and link it with this issue. Thanks.

**Comment by torkiljohnsen** [comment]
🎉  👍

**Comment by PierreLvx** [comment]
Just tested here. I am afraid this is only a partial fix.

We no longer have issues with files using a single group use declaration. However, with more than one group there comes the `Unexpected token` again.

Unfortunately, I don't have the time to dig deeper right now.

**Comment by manuelpichler** [comment]
@PierreLvx could you please provide example code that fails?

**Comment by PierreLvx** [comment]
We narrowed it down to one package (https://github.com/stripe/stripe-php), which we use with Laravel 5.

If we do :

```php
use Stripe\{
    Stripe,
    Coupon,
    Customer,
    Subscription
};
```

The tests fail.

Actually, any of the following use statement will fail :

```php
use SomeNamespace\{
   Foo,
   Bar
};
```

However, something like this will pass :

```php
use SomeOtherNameSpace\Names\{
   Bob,
   Alice
};

**Comment by manuelpichler** [comment]
@PierreLvx thx for this reproducible, I will investigate asap.
