### ISSUE TITLE
Custom Property Setting in Ruleset Requires Excluding Rule First

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#33]
While trying to customize the settings for one PHPMD Rule, I discovered that the property could not be overridden by only specifying the new property value. It was necessary to first exclude the rule and then add it back with the desired property setting. For example:

ruleset.xml:

``` xml
<?xml version="1.0"?>
<ruleset name="C D Chase ruleset"
    xmlns="http://pmd.sf.net/ruleset/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0 http://pmd.sf.net/ruleset_xml_schema.xsd"
    xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">
  <description>
  Custom PHPMD Rules
  </description>
  <rule ref="rulesets/codesize.xml"/>
  <rule ref="rulesets/naming.xml"/>
  <rule ref="rulesets/unusedcode.xml"/>
  <rule ref="rulesets/design.xml">
    <exclude name="CouplingBetweenObjects"/>
  </rule>
  <rule ref="rulesets/design.xml/CouplingBetweenObjects">
    <properties>
        <property name="minimum" value="20"/>
    </properties>
  </rule>
</ruleset>
```

Now this could just be a lack of clarity in documentation, and this is the intended behavior. If so, the documentation should be supplemented with an example similar to above.

I thought I had read somewhere that the property could be simply added and it would override the default value, but I can't find that documentation now. If I track it down, I'll return and add it here.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/12615203']

**Comment by torkiljohnsen** [comment]
We just past the 4 year anniversary for this issue! 🎺 🎵 

***bump***

**Comment by thiagotalma** [comment]
:birthday:

**Comment by HemaliSavaliya** [comment]
How to set this custom file in netbeans 8.1?

**Comment by zebimax** [comment]
Having same problems in 2019)

**Comment by Philipp91** [comment]
I had the same problem as Manuel, specifically with `CouplingBetweenObjects`, whereas all other overrides worked for me. Turns out the property [was](https://github.com/phpmd/phpmd/commit/a206415af3d40a3a478dc4ca0d26f8dd36b6689c) [renamed](https://github.com/phpmd/phpmd/commit/3333326eff64db6e21233e603fed51659ef5208e) _after_ the latest release, so the documentation and the installed package don't match. Anyway, `s/maximum/minimum` fixed the problem for me.

**Comment by ravage84** [comment]
Finally documented through #565
