### ISSUE TITLE
unable to use .phar due unsupported signature error

### ISSUE THREAD

**Issue by glensc** [phpmd/phpmd#332]
seems same issue as in phpunit: https://github.com/sebastianbergmann/phpunit/issues/1948

please see if you can also build more compatible phar file:
https://github.com/sebastianbergmann/phpunit/issues/1948#issuecomment-155438262
https://github.com/sebastianbergmann/phpunit/issues/1948#issuecomment-155437695
https://github.com/sebastianbergmann/phpunit/commit/4ef58ab03115c22c05ad05a33d0fee5986a2b208

**Comment by kylekatarnls** [comment]
Seems phar-related issue and not reproductible with our latest phpmd.phar.

**Comment by steinhaug** [comment]
Make sure you are uploading the PHAR files as BINARY, as ASCHII transfer will make them behave like described here. Hope it helps.
