### ISSUE TITLE
bz2 extension required for phar distrib

### ISSUE THREAD

**Issue by llaville** [phpmd/phpmd#336]
Hello,

I've just downloaded the phar distribution following instruction at http://phpmd.org/download/index.html

When I run it with PHP 5.6.16, I got following error 

Fatal error: Uncaught exception 'PharException' with message 'bz2 extension is required for bzip2 compressed .phar file

I suggest to check first if extension is loaded before running PHPMD base code in phar container !

**Comment by intekhabrizvi** [comment]
same issue on PHP v7 (PHP 7.0.4-6+deb.sury.org~trusty+5 (cli)) also.

**Comment by notflip** [comment]
Any update on this? Same issue on 7.0.3

**Comment by alfirin** [comment]
```
PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ phpmd
PHP Fatal error:  Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/local/bin/phpmd" in /usr/local/bin/phpmd:8
Stack trace:
#0 /usr/local/bin/phpmd(8): Phar::mapPhar('phpmd.phar')
#1 {main}
  thrown in /usr/local/bin/phpmd on line 8
```

**Comment by mechagear** [comment]
Check symlink at /etc/php/7.0/cli/ it points the wrong mods-available directory (/etc/php/mods-available instead of /etc/php/7.0/mods-available where bz2.ini is located)

**Comment by bandanh** [comment]
@mechagear was right, bz2 was missing
```
sudo apt update
sudo apt install php-bz2
```
Fixed it for me

**Comment by ravage84** [comment]
We should document the bz2 requirement for the phar.

**Comment by digitaldreams** [comment]
@bandanh  your solution works for me. Thanks a lot
