### ISSUE TITLE
phpmd: PHP Notice:  Use of undefined constant T_CHARACTER

### ISSUE THREAD

**Issue by aliceinwire** [phpmd/phpmd#338]
16:06:12 PHP Mess Detector
         phpmd: PHP Notice:  Use of undefined constant T_CHARACTER - assumed 'T_CHARACTER' in C:\xampp\php\pear\PHP\Depend.php on line 538
         PHP Stack trace:
         PHP   1. {main}() C:\xampp\php\phpmd:0
         PHP   2. PHP_PMD_TextUI_Command::main() C:\xampp\php\phpmd:48
         PHP   3. PHP_PMD_TextUI_Command->run() C:\xampp\php\pear\PHP\PMD\TextUI\Command.php:154
         PHP   4. PHP_PMD->processFiles() C:\xampp\php\pear\PHP\PMD\TextUI\Command.php:128
         PHP   5. PHP_PMD_Parser->parse() C:\xampp\php\pear\PHP\PMD.php:203
         PHP   6. PHP_Depend->analyze() C:\xampp\php\pear\PHP\PMD\Parser.php:128
         Exclude UpdatePackage.php from PHP Mess Detector analysis.

**Comment by ravage84** [comment]
@aliceinwire could you provide more information about the environment and the phpmd version used?

**Comment by aliceinwire** [comment]
PEAR Version: 1.10.1
PHP Version: 7.0.1
Zend Engine Version: 3.0.0
Running on: Windows NT 6.3 build 9600 (Windows 8.1 Professional Edition) i586

C:\xampp\php\phpmd.bat C:/Users/ITCOLL~1/AppData/Local/Temp/___0.tmp/DbAction.php xml codesize,controversial,design,naming,unusedcode

phpmd.bat
if "%PHPBIN%" == "" set PHPBIN=C:\xampp\php\.\php.exe
if not exist "%PHPBIN%" if "%PHP_PEAR_PHP_BIN%" neq "" goto USE_PEAR_PATH
GOTO RUN
:USE_PEAR_PATH
set PHPBIN=%PHP_PEAR_PHP_BIN%
:RUN
"%PHPBIN%" "C:\xampp\php\phpmd" %*

**Comment by ravage84** [comment]
Could be related to PHP 7, though our tests run through in Travis:
https://travis-ci.org/phpmd/phpmd/jobs/100560175

Could you re-verify your problem on PHP 5.x, please?

**Comment by aliceinwire** [comment]
sorry I cannot test with php 5.x as now

**Comment by manuelpichler** [comment]
@aliceinwire which version of pdepend did you use, because in the latest version there is already a *[fallback](https://github.com/pdepend/pdepend/blob/2.2.2/src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php#L137)* for this missing constant implemented.

**Comment by manuelpichler** [comment]
This is fixed since phpmd@2.3.3
