### ISSUE TITLE
Warnings for "static" calls

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#34]
"static" calls are considered bad practice if you want to follow the DI principle entirely. I would love a rule set which emits warnings about "static" calls in classes.

Also they introduce a static dependency which is generally considered bad practice.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/24140907']

**Comment by ravage84** [comment]
@martinlindhe thanks for pointing out. Yes one can use ``StaticAccess`` for that. Closing
