### ISSUE TITLE
Missing DevelopmentCodeFragment doc?

### ISSUE THREAD

**Issue by feryardiant** [phpmd/phpmd#340]
I can see any [documentation](http://phpmd.org/rules/design.html) about [DevelopmentCodeFragment](https://github.com/phpmd/phpmd/blob/master/src/main/resources/rulesets/design.xml#L194-L227)

**Comment by tariq86** [comment]
It's showing up now, but with small display issue reported in #532 .

I believe this issue can be closed.

**Comment by feryardiant** [comment]
Awesome, thanks @tariq86 

Small request, can we just keep this issue opened until actually available [here](https://phpmd.org/rules/index.html) please?

**Comment by tvbeek** [comment]
I see that the page is now updated with the missing part so I close this issue.
