### ISSUE TITLE
Unexpected token when using PHP7’s null coalesce operator

### ISSUE THREAD

**Issue by jonnybarnes** [phpmd/phpmd#347]
`$var = $otherVar ?? 'default';` gives `Unexpected token: ??`.

**Comment by ravage84** [comment]
This should probably be fixed in PDepend.

**Comment by torkiljohnsen** [comment]
👍  Ran into this too.

**Comment by MarcFRICOU** [comment]
same problem

**Comment by zachrattner** [comment]
Confirmed for me too.

**Comment by tyler36** [comment]
Confirmed for me too.

**Comment by JeroenDeDauw** [comment]
Confirmed with PHPMD 2.4.3

**Comment by FGM** [comment]
Still present in today's dev head.

**Comment by marcusesa** [comment]
😞

**Comment by lgoral** [comment]
I think problem is with missing   TOKEN_PARSE for token_get_all in https://github.com/pdepend/pdepend/blob/master/src/main/php/PDepend/Source/Language/PHP/PHPTokenizerInternal.php#L651 

```
if (version_compare(phpversion(), '5.3.0alpha3') < 0) {
            $tokens = PHPTokenizerHelperVersion52::tokenize($source);
        } elseif (version_compare(phpversion(), '7.0') > 0) {
            $tokens = token_get_all($source, TOKEN_PARSE);
        } else {
            $tokens = token_get_all($source);
        }
```

**Comment by MatissJanis** [comment]
This issue has been fixed on PDepend. Can a new PHPMD version be released with this fix?

**Comment by wandersonwhcr** [comment]
:+1:

**Comment by torkiljohnsen** [comment]
Still awaiting new PDepend release perhaps?

**Comment by MisterGlass** [comment]
Has anyone found an interim fix? I have a new PHP7 codebase and want to turn on PHPMD, but I cant until it support the new operators.

**Comment by webaaz** [comment]
:+1:

**Comment by azzeddinefaik** [comment]
same in here any fix for this ?

**Comment by wandersonwhcr** [comment]
Até que enfim!

We have a new PDEPEND tag since March!

Please, update your composers! :smile:

**Comment by wandersonwhcr** [comment]
https://github.com/pdepend/pdepend/releases/tag/2.2.6

**Comment by azzeddinefaik** [comment]
$ phpmd ./src  xml cleancode   --reportfile ./testphp.xml --suffixes php    > testphpmd.log
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
PHP PDepend\Source\Parser\UnexpectedTokenException:  Unexpected token: ??, line: 217, col: 42, file: /Users/azzeddinefaik/Workspace/php-test/mongodm/src/Collection.php. in phar:///usr/local/bin/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 2845
PHP Stack trace:

My issue is with phpmd not PDEPEND.

**Comment by wandersonwhcr** [comment]
Please, run: `composer outdated | grep pdepend` and post results here.

**Comment by azzeddinefaik** [comment]
$ pdepend --version
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0

Warning: Module 'mongodb' already loaded in Unknown on line 0
PDepend 2.2.6

**Comment by wandersonwhcr** [comment]
I think your installation of PHPMD is a `phar`. Again, I think the `phpmd.phar` have a `pdepend` installation internally and still with version `2.2.4`.

If you use Composer, you simply need to update your `composer.phar` with `composer update pdepend/pdepend`.

**Comment by jonnybarnes** [comment]
`pdepend` v2.2.6 fixes this

**Comment by MisterGlass** [comment]
Confirmed. Not sure why I have 2.2.4 (my project is newer than the 2.2.6 release) but I forced an update with `composer update pdepend/pdepend` and it works now. Thanks!

**Comment by azzeddinefaik** [comment]
pdepend fixed thanks @wandersonwhcr , but I got new error 

16
PHP OutOfBoundsException:  Property "exceptions" does not exist. in /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/AbstractRule.php on line 380
PHP Stack trace:

**Comment by wandersonwhcr** [comment]
@azzeddinefaik I'm sorry, but with this error I can't help you.

Please, search if another issue has your problem or create a new one.
