### ISSUE TITLE
Please provide TLS/SSL download option

### ISSUE THREAD

**Issue by client9** [phpmd/phpmd#348]
Hello,

I noticed you are only supporting HTTP downloads.

re:
wget -c http://static.phpmd.org/php/latest/phpmd.phar

Would like to see this under https / TLS.

thanks,

nickg

**Comment by manuelpichler** [comment]
All the phpmd.org and static.phpmd.org traffic should now go through HTTPS.

**Comment by mosbth** [comment]
This made [my project's Travis build](https://travis-ci.org/mosbth/anax/jobs/113172392#L232-L246) fail.

```
$ wget -c http://static.phpmd.org/php/latest/phpmd.phar
--2016-03-04 08:28:14--  http://static.phpmd.org/php/latest/phpmd.phar
Resolving static.phpmd.org (static.phpmd.org)... 78.47.238.172
Connecting to static.phpmd.org (static.phpmd.org)|78.47.238.172|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://static.phpmd.org/php/latest/phpmd.phar [following]
--2016-03-04 08:28:14--  https://static.phpmd.org/php/latest/phpmd.phar
Connecting to static.phpmd.org (static.phpmd.org)|78.47.238.172|:443... connected.
ERROR: cannot verify static.phpmd.org's certificate, issued by `/C=DE/ST=NRW/L=Witten/O=Internet Widgits Pty Ltd/CN=*.ruhrtal.net/emailAddress=admin@ruhrtal.net':
  Self-signed certificate encountered.
    ERROR: certificate common name `*.ruhrtal.net' doesn't match requested host name `static.phpmd.org'.
To connect to static.phpmd.org insecurely, use `--no-check-certificate'.
The command "wget -c http://static.phpmd.org/php/latest/phpmd.phar" failed and exited with 5 during .
```

Fixed it by adding `--no-check-certificate`.
```
$ wget --no-check-certificate -c https://static.phpmd.org/php/latest/phpmd.phar
```

**Comment by ravage84** [comment]
@manuelpichler How about using a [Let's Encrypt](https://letsencrypt.org/) cert? I have no experience with installing it on a dedicated server or whatever you use for phpmd.org, but on our shared hosting partner's cPanel it is a breeze.

**Comment by manuelpichler** [comment]
@ravage84 it is a Let's Encrypt certificate.

**Comment by manuelpichler** [comment]
@ravage84 it is a Let's Encrypt certificate

Btw. the organisation mentionend in the output **Internet Widgits Pty Ltd** was never-ever used by me. It seems here something totally different was/is broken, se here https://supportforums.cisco.com/discussion/12580191/malware-other-self-signed-ssl-certificate-only-allow-source-or-destination

**Comment by ravage84** [comment]
Yeah, I guess the problem is Travis'side.
Probably their ISP uses some caching (which would make sense as they often fetch the same stuff). That caching server might have returned a self-signed cert...
