### ISSUE TITLE
Warnings for "new" statements in class

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#35]
"new" statements are considered bad practice if you want to follow the DI principle entirely. I would love a rule set which emits warnings about "new" statements in classes.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/24140881']

**Comment by ravage84** [comment]
Closing as there seems to be no big demand and the real world use is rather questionable, too.

**Comment by kylekatarnls** [comment]
I agree, and DI is far from being the only pattern. Then this pattern does not imply that every object should be injected. To build a typed nodes AST, it would be insane to use DI pattern.

This would be fine for a custom rule/plugin. It does not need to be in the core library.
