### ISSUE TITLE
Unexpected tokens

### ISSUE THREAD

**Issue by krzysiekpiasecki** [phpmd/phpmd#351]
PHP: 7.0.3

Unexpected tokens founds when declaring:

use function foo
use const FOO

Log:
Unexpected token: const ...
Unexpected token: function ...

**Comment by ravage84** [comment]
Probably a problem of pdepend.

**Comment by krzysiekpiasecki** [comment]
Actually I'm sure of it. I will report it them.

**Comment by schnittstabil** [comment]
I've made a PR(https://github.com/pdepend/pdepend/pull/252) a week ago :grin:
