### ISSUE TITLE
exclude not working

### ISSUE THREAD

**Issue by joepetjr** [phpmd/phpmd#356]
phpmd 2.4.2

command line exclude not working such as;

--exclude="/home/jjpet/svnWork/225161/includes/config/" and variations without the = " and trailing /

**Comment by ravage84** [comment]
I think we should document this properly. To my knowledge without the equals sign should be correct.

**Comment by joepetjr** [comment]
a sample of the command and result are as follows, any variation of the command and the results are the same;  
[~]$ phpmd --version
PHPMD 2.4.2
[~]$ phpmd ~/svnWork/jjpet_trunk20160321/includes/ text design --reportfile mdresults --exclude /home/jjpet/svnWork/jjpet_trunk20160321/includes/config/

viewing the end of mdresults file shows;
/home/jjpet/php/SystemFiles/jjpet_trunk20160321/includes/config/not_the_actual_file_name   -   Unexpected token: __halt_compiler, line: 1, col: 17, file: /home/jjpet/php/SystemFiles/jjpet_trunk20160321/includes/config/not_the_actual_file_name.

i figured out the exclude wasn't working because running this phpmd command in a bash script kills the script, as in; the script wont continue past the phpmd command.  also, the file in question does in fact contain the halt compiler command.

**Comment by kovacsbalu** [comment]
Same here with versions >= 2.3.1.

**Comment by ArturGoldyn** [comment]
Hi, can we please proceed with that? It's messing up with our project too :+1:

**Comment by sveneld** [comment]
command should be written like this
--exclude /home/jjpet/svnWork/225161/includes/config/*
because filename comparing with preg_match function

**Comment by ravage84** [comment]
@sveneld would you be willling to put a PR with an extension to the current documentation?

**Comment by sveneld** [comment]
ok, in a few days
