### ISSUE TITLE
Unexpected token: ??

### ISSUE THREAD

**Issue by voksiv** [phpmd/phpmd#358]
Check result:
**/builds/php/phportal/beget/lib/network/lib/Reserver.php	-	Unexpected token: ??, line: 300, col: 41, file: /builds/php/phportal/beget/lib/network/lib/Reserver.php.**
Php7 feature:
**https://wiki.php.net/rfc/isset_ternary**

**Comment by ravage84** [comment]
Yep, this is already known, see https://github.com/phpmd/phpmd/issues/347
