### ISSUE TITLE
Adding the phpmd to brew cask

### ISSUE THREAD

**Issue by zhenglaizhang** [phpmd/phpmd#364]
First of all, thanks for the great work on the powerful tool. Recently the tool helps me a lot. 

I am considering to commit to the homebrew repo to make the installation of the tool more convenient via `brew cask install phpmd`. But first of all, I want to make sure following items with you guys:

1. You guys are ok with my change to add the phpmd to brew cask
2. What's the license of the phpmd

Again, thanks for the great effort to the project. 👍

**Comment by ravage84** [comment]
Hi @zhenglaizhang ,

Thanks for reaching out on us about this.

Actually I have no idea about homebrew repos or the brew tool. Never used it.
Can you give us more insight?
But anyway, I think I can answer this for @manuelpichler, too:

1. Depending on the implications of adding phpmd to brew cask, I would say we are totally fine with this. :smirk_cat:
Currently, I don't think @manuelpichler  or me has interest in maintaining another phpmd related repo as we both are busy enough :construction_worker: But if there will be interest of any maintainer of phpmd in the future, I would say, the condition would be to let this person have some power over that brew repo.
2. The license of phpmd is "BSD-3-Clause". A very permissive license. https://opensource.org/licenses/BSD-3-Clause

**Comment by zhenglaizhang** [comment]
Hi @ravage84 ,

Thanks for the quick response and detailed info. You are so helpful -:)
homebrew is the missing package manager for OS X and is very convenient for package or app management, it's very popular and now one ecosystem. I used the brew to management almost all my OS X packages and apps. The reason why I want to add phpmd to homebrew is that I want to keep things simple and easy to manage.

I noticed that the download link for the latest phpmd  http://static.phpmd.org/php/latest/phpmd.phar so we could just point the download link in homebrew to this, and if we don't change the endpoint in the future, we could just leave it in homebrew as it goes and if future anybody meets with the issue, they are also ok to fire one issue to the homebrew github repo and update the brew definitions, the updating process is very easy. 

I would try to add the phpmd to the homebrew tomorrow, please kindly let me know if you have any concerns today. 

Again, thanks for the great work on the project and quick detailed info, you guys are so nice!

**Comment by ravage84** [comment]
OK, sounds good. I'm going to close this ticket now. But please keep us updated here.
