### ISSUE TITLE
Error with PHP 5.3.3 on CentOS 6.7

### ISSUE THREAD

**Issue by phackwer** [phpmd/phpmd#366]
phpmd-ci:
    [phpmd] PHP Fatal error:  Can't inherit abstract function PHPMD\Rule::apply() (previously declared abstract in PHPMD\AbstractRule) in phar:///usr/bin/phpmd/src/main/php/PHPMD/AbstractRule.php on line 54

**Comment by phackwer** [comment]
I found out it was the version.

**Comment by duckbrain** [comment]
#320 References the issue with PHP 5.3.3.
