### ISSUE TITLE
Document "exclude-pattern" feature

### ISSUE THREAD

**Issue by ravage84** [phpmd/phpmd#373]
Implemented in 2.1.0, it was not documented though.

https://github.com/phpmd/phpmd/pull/100
https://github.com/phpmd/phpmd/blob/7c293efb29c54f10398e4c9667043c0c3342e1a7/CHANGELOG#L238
https://github.com/phpmd/phpmd/blob/7c293efb29c54f10398e4c9667043c0c3342e1a7/src/test/resources/files/rulesets/exclude-pattern.xml#L21
http://pmd.sourceforge.net/pmd-5.0.4/howtomakearuleset.html#Excluding_files_from_a_ruleset

**Comment by JeroenDeDauw** [comment]
Is this the correct way to exclude multiple things?

```
    <exclude-pattern>*Validator</exclude-pattern>
    <exclude-pattern>FunFunFactory.php</exclude-pattern>
```

**Comment by ravage84** [comment]
I doubt it, try providing a comma divided list of paths

**Comment by adamcameron** [comment]
@JeroenDeDauw (/ @ravage84) that does actually seem to be the way it's been implemented. Comma-separated list does not work; separate elements does. Not sure this is for the best, but at least it ought to be documented thus.

**Comment by sveneld** [comment]
> Is this the correct way to exclude multiple things?
> 
> ```
>     <exclude-pattern>*Validator</exclude-pattern>
>     <exclude-pattern>FunFunFactory.php</exclude-pattern>
> ```

it should be written as
`
    <exclude-pattern>*Validator*</exclude-pattern>
    <exclude-pattern>*FunFunFactory.php*</exclude-pattern>
`
because filename comparing with preg_match function

**Comment by ravage84** [comment]
@sveneld would you be willling to put a PR with an extension to the current documentation?

**Comment by sveneld** [comment]
ok, in a few days

**Comment by sveneld** [comment]
it can be closed
