### ISSUE TITLE
unique identifier to distinguish from pmd

### ISSUE THREAD

**Issue by andykais** [phpmd/phpmd#375]
The output xml files of PMD and PHPMD tools are almost identical. Without knowing which program generated them, it is programatically tricky to identify which tool the file derived from. Would you consider changing the top level `<pmd></pmd>` tag to `<phpmd></phpmd>`? A unique attribute like `tool="phpmd"` would work just as well.

Currently, the best identifier I see is `version="@project.version@"` which is not used by PMD. Why do you use this format? Is it a permanent change?

**Comment by ravage84** [comment]
Changing the tag would be a backward incompatible change.
Adding an attribute seems safe to me, though.

The last answer I cannot answer you.
May be @manuelpichler can.

**Comment by kylekatarnls** [comment]
Both XML are supposed to be compatible (same XSD), you could in theory merge files from both PMD and PHPMD in a project using both Java and PHP (I known, I know, looks like Si-Fi scenario), and the whole thing would be the list of violations of your project with no consideration of the language (file extension would be enough to know).

So it should be done only with an attribute (or additional tag), not with a tag change clearly. And ideally, it should use a syntax accepted by the original XSD format.
