### ISSUE TITLE
Add rule that detects access to an undefined variable

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#38]
Implement a rule that detects property or method access on a variable that is not defined.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/11009501']

**Comment by ava-dylang** [comment]
:+1: how do php people even live without any tool to do this. :moyai:-age

**Comment by ravage84** [comment]
Probably related to or even a duplicate of https://github.com/phpmd/phpmd/issues/65

**Comment by ravage84** [comment]
Closing as it's a duplicate of https://github.com/phpmd/phpmd/issues/65
