### ISSUE TITLE
Unexpected token: EMPTY

### ISSUE THREAD

**Issue by torkiljohnsen** [phpmd/phpmd#389]
PHPMD does not let me use a class constant called `EMPTY`. Sample:

``` php
class Test
{
    const EMPTY = 'empty';
}
```

I suspect it's being too strict since "As of PHP 7.0.0 these keywords are allowed as as property, constant, and method names of classes, interfaces and traits, except that class may not be used as constant name."

http://php.net/manual/en/reserved.keywords.php

**Comment by MidnightDesign** [comment]
This is still a problem for me. I've got PDepend 2.5.2 and PHPMD 2.6.0.
