### ISSUE TITLE
Unused Local Variable warning

### ISSUE THREAD

**Issue by kamranahmedse** [phpmd/phpmd#390]
I am getting unused local variable for `$appId = $order['app_id'] ?? 0;` warning on below code. 

``` php
// ...
$appId = $order['app_id'] ?? 0;
$userOrigin = $order['headers']['origin'] ?? '';

if (empty($userOrigin)) {
    $userOrigin = $order['headers']['referer'][0] ?? false;
    $userOrigin = get_base_url($userOrigin, false);

    if (empty($userOrigin)) {
        $userOrigin = !empty(Constants::DEFAULT_APP_URLS[$appId]) ? Constants::DEFAULT_APP_URLS[$appId] : 'http://johndoe.com';
    }
}

$request->orderDetail = [
    'app_id' => $appId,
    'locale' => $order['headers']['x-locale'][0],
    'origin' => trim($userOrigin, '/'),
];
// ...
```

While you can see that `$appId` is being used in two places, once at `Constants::DEFAULT_APP_URLS[$appId]` and second in the `$request->orderDetail` array i.e. `'app_id' => $appId`.

Also, I am getting the similar error for `$dataset` in the below code

``` php
$dataset = [];
foreach ($someData as $item) {
    $dataSet[] = $item['some_key'];
}
```

**Comment by ravage84** [comment]
Could be related to https://github.com/phpmd/phpmd/issues/446 or it could be because of the coalesce operator, though it should be fixed by now. Since I have no php 7 box at hand, I cannot confirm this.

@kamranahmedse do you still see this issue?

**Comment by kylekatarnls** [comment]
I don't have any warning using the same code. So I assume it's fixed yet. If you still have the issue, please provide a minimal code chunk to get the incorrect warning and I will re-open.
