### ISSUE TITLE
Incorrect property name used for CouplingBetweenObjects

### ISSUE THREAD

**Issue by jhoff** [phpmd/phpmd#392]
https://phpmd.org/rules/design.html#couplingbetweenobjects

| Name | Default Value | Description |
| --- | --- | --- |
| minimum | 13 | Maximum number of acceptable dependencies. |

Pretty sure the property name should be `maximum` not `minimum`

Note: This isn't a documentation error. Using `maximum` has no effect. To set the `maximum` you have to declare the `minimum`

**Comment by ravage84** [comment]
Hey @jhoff thanks for the report. Could you open a PR to fix that?

**Comment by jhoff** [comment]
Sure... out of curiosity, do you have any estimates on the next release?

**Comment by jhoff** [comment]
:+1:
