### ISSUE TITLE
Wording Error in Ruleset Documentation at phpmd.org/rules/index.html

### ISSUE THREAD

**Issue by madnight** [phpmd/phpmd#398]
"Design Rules: The **Code Size** Ruleset contains a collection of rules that find software design related problems."

Should be:

Design Rules: The **Design** Ruleset contains a collection of rules that find software design related problems.

**Comment by ravage84** [comment]
Resolved in https://github.com/phpmd/phpmd/commit/c51ea72761fdaf38c1787658f07e2d20b1141ae0

Thanks for reporting!
