### ISSUE TITLE
GPLv3 WCV documentation and BSD

### ISSUE THREAD

**Issue by Isinlor** [phpmd/phpmd#399]
Hello, I have small concern about licensing of this library.

Is it ok for this library to use Web Content Viewer licensed on GPLv3 while library itself is on BSD license? I can see that you are using WCV code eg. in ezt templates and to my best knowledge it would enforce GPLv3.

Can I be assured that it was taken into consideration and this library is not de facto on GPLv3 license?

Thanks for help! And great library btw ;) !

**Comment by ravage84** [comment]
@manuelpichler can you say something about the licensing concerns, mentioned above?

**Comment by manuelpichler** [comment]
@Isinlor you can be sure that the usage of WCV is totally okay here.

a) Because we only have *.ezt templates and *.ini files in our code base, no source code from wcv
b) The core developer of wcv is one of my best friends

/cc @ravage84
