### ISSUE TITLE
Detect empty catch blocks

### ISSUE THREAD

**Issue by greg0ire** [phpmd/phpmd#407]
Hello,

this is a feature request to detect empty catch blocks. I'm talking about this kind of practice:

``` php
<?php
try {
    some_function_call();
} catch (\Exception $e) {
    // do nothing, not even logging the exception
}
```

**Comment by ravage84** [comment]
Hi @greg0ire, nice idea, could be useful.
Are you willing to put up a PRf or this?

**Comment by ravage84** [comment]
Sorry, misclicked.

**Comment by greg0ire** [comment]
Yes I am :)

**Comment by ravage84** [comment]
Try to find a similar rule and look how it was implemented.
Unfortunately, we have no "how to implement a rule" guide.
Might be a good addition, though.

Anyway, what rule set would you put it in?

**Comment by greg0ire** [comment]
>  Unfortunately, we have no "how to implement a rule" guide.

Guess I'll add things to CONTRIBUTING.md if this turns out to be difficult then ;)

"design" seems the most well-suited for that, isn't it?

**Comment by ravage84** [comment]
@greg0ire, you can add things to CONTRIBUTING.md in a separate PR.

**Comment by ravage84** [comment]
@greg0ire due to the lack of any better rule set, I'm fine with Design, though if we ever create a PHPMD, we might reorganize these rule sets :smirk_cat:

**Comment by greg0ire** [comment]
Yeah design seems a bit vague… also, is adding a new rule considered a BC-break? It might make some test suites suddenly fail, right?

**Comment by ravage84** [comment]
Well, it could be seen a such by some.
But we will release this rule in 2.5.0 or another minor release.
According to SemVer adding functionality in a minor release is OK.
I'm fine with this situation, but thanks for caring.

**Comment by kenguest** [comment]
Hi - has this seen light of day into a release yet? I'd love to have something automatic to lambast people over writing empty catch blocks :-)

**Comment by ravage84** [comment]
@kenguest not yet, sorry. See #408

**Comment by kenguest** [comment]
hi @ravage84  - thanks for such a quick response, much appreciated.
