### ISSUE TITLE
Can't exclude a folder test

### ISSUE THREAD

**Issue by quentincurtet** [phpmd/phpmd#414]
Hi,

I want PHPMD in my project, but i don't want it in my test folder.
I tried with `<exclude-pattern>*/myFolder/*</exclude-pattern>`

But it didn't work.

Can someone help me ?

**Comment by ravage84** [comment]
Actually I  am not sure if we support the asterisk sign...
We really should document this feature #373...

**Comment by quentincurtet** [comment]
So what is the answer ?

**Comment by quentincurtet** [comment]
Because, even with the links you gave, i can't solve my problem.

**Comment by ravage84** [comment]
May be this helsp:
http://pmd.sourceforge.net/pmd-5.0.4/howtomakearuleset.html#Excluding_files_from_a_ruleset

Test file:
https://github.com/phpmd/phpmd/blob/2.5.0/src/test/resources/files/rulesets/exclude-pattern.xml

Related PR:
https://github.com/phpmd/phpmd/pull/100
