### ISSUE TITLE
PHP OutOfBoundsException:  Property "exceptions" does not exist. in 

### ISSUE THREAD

**Issue by azzeddinefaik** [phpmd/phpmd#415]
PHP OutOfBoundsException:  Property "exceptions" does not exist. in /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/AbstractRule.php on line 380
PHP Stack trace:
PHP   1. {main}() /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/bin/phpmd:0
PHP   2. PHPMD\TextUI\Command::main() /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/bin/phpmd:122
PHP   3. PHPMD\TextUI\Command->run() /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php:173
PHP   4. PHPMD\PHPMD->processFiles() /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php:130
PHP   5. PHPMD\Parser->parse() /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php:222
PHP   6. PDepend\Engine->analyze() /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php:123
PHP   7. PHPMD\Parser->close() /Users/azzeddinefaik/.composer/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php:345
PHP   8. PDepend\Source\AST\ASTNamespace->accept() /Users/azzeddinefaik/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php:177

**Comment by tvbeek** [comment]
@azzeddinefaik can you explain how you got this error? Then we can verify and try to fix it.

**Comment by kylekatarnls** [comment]
@azzeddinefaik I close this as not reproductible but if you can provide an example to get this error, I would re-open.
