### ISSUE TITLE
Revisit the AppVeyor builds

### ISSUE THREAD

**Issue by ravage84** [phpmd/phpmd#417]
Currently, the AppVeyor builds seem to break.

We should have a look at that.

Might help:
https://blog.wyrihaximus.net/2016/11/running-php-unit-tests-on-windows-using-appveyor-and-chocolatey/

**Comment by Arcanemagus** [comment]
From what I can see the builds are failing due to trying to install the KB2919355 and KB2919442 patches, and not properly handling the "already installed" error code they return of `1058`.

I'm pretty sure this is an issue with the Chocolatey package itself.

**Comment by ravage84** [comment]
@Arcanemagus thanks for the feedback. You seem to be quite knowledgable about this. Would you want to try to fix it?

**Comment by Arcanemagus** [comment]
I'm not sure there is anything we _can_ do to fix it (I'm seeing this on my `linter-phpmd` and `linter-phpcs` builds), since the issue is in the Chocolatey script. I've sent in a message to the author of that Chocolatey package, hopefully this can be resolved there soon as I _really_ don't want to have to mess with installing it manually again 😛.

**Comment by Arcanemagus** [comment]
Haven't heard anything back, and as I don't like merging anything that causes `master` to fail I'm putting the changes from this into place: https://github.com/AtomLinter/linter-phpcs/pull/219

I'm _sure_ there are better ways to get PHP installed on AppVeyor manually, but this hacked together thing works for the moment if you were interested.

**Comment by Arcanemagus** [comment]
Okay, after a bit more testing and some help from people on the Chocolatey gitter, I've updated the linked PR above to a method that lets us still use the package, but ensures it will actually work properly.

Do you want a PR here implementing that?
