### ISSUE TITLE
Allow PHP_Depend optimization mode to be specified from the command line

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#42]
Allow pdepend's option, --optimization, to be specified from phpmd's command line. 

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/9355909']

**Comment by ravage84** [comment]
Closing this as the ``optimization`` options seems to be deprecated by now:

https://github.com/pdepend/pdepend/blob/2.5.0/src/main/php/PDepend/TextUI/Command.php#L207
