### ISSUE TITLE
Mess detection for unintentonal assigments in foreach

### ISSUE THREAD

**Issue by blurayne** [phpmd/phpmd#420]
It's not the first time I encounter something like the following. 

So far this is a special case:

```
php > $children = [[1, 2, 3, 4]];
php > $otherChildren = [[1, 2]];
php > foreach ($children as &$child) {
php {     $child[] = 5;
php { }
php > $returnArray = $children;
php > foreach ($otherChildren as $child) {
php {     //do something
php { }
php > print_r($returnArray);
Array
(
    [0] => Array
        (
            [0] => 1
            [1] => 2
        )

)

```

**Comment by ravage84** [comment]
@blurayne could you please reformat your code for better readability? Please don't paste the REPL output or whatever this is.

In what situations would you emit a PHPMD violation?
Would you like to create a PR to implement such a rule?

**Comment by tvbeek** [comment]
Closing because we didn't get the feedback for this issue.
