### ISSUE TITLE
Support for 7.1 nullable types

### ISSUE THREAD

**Issue by irfane** [phpmd/phpmd#422]
Fatal error: Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\AbstractASTCallable::addChild() must implement interface PDepend\Source\AST\ASTNode, null given, called in vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 97 and defined in vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php:143

I get this error when parsing 

```
    /**
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }
```

I'm guessing phpmd doesn't support PHP 7.1 yet.

**Comment by ravage84** [comment]
This needs to be done in Pdepend.
