### ISSUE TITLE
Collaboration with Codacy

### ISSUE THREAD

**Issue by machadoit** [phpmd/phpmd#425]
Hi there, João Machado from [Codacy](https://www.codacy.com) here.

We have a PHPMD integration, so that everyone that uses our website can get PHP static analysis. You can check it at https://github.com/codacy/codacy-phpmd.

Would you guys be interested on mentioning us as proud users of PHP Mess Detector? You can also add your phpmd at Codacy to check it out, we are free for open source projects.

**Comment by ravage84** [comment]
Hi @machadoit 

Glad you like PHPMD.

Can you give us a quick explanation in how Codacy is different to/better than other tools, such as Scrutinizer CI?

**Comment by machadoit** [comment]
We do provide the same kind of features of other tools, however we do support a lot of languages, and are really open source friendly. Our open source users have access to every single feature of our product for free.

Each tool integration is made with dockers, and any user can create a docker for a language that we don't support yet, and suddenly we will have support for it. As an example of a tool made by one of our users, you can check https://github.com/codacy/codacy-coffeelint

**Comment by ravage84** [comment]
We are quite busy right now.
When I get the time, I'll have a look. Probably not before spring 2017.

**Comment by machadoit** [comment]
Thank you, if you guys are interested, I can create a PR for your website, with a new section like "Users" or "Integrations", where tools like Codacy could be referenced. Otherwise we will just postpone it till mid 2017.

**Comment by ravage84** [comment]
I'll discuss that with @manuelpichler 
We are in no rush. Thanks
