### ISSUE TITLE
Can't inherit abstract function PHPMD\Rule::apply()

### ISSUE THREAD

**Issue by viorelgheba** [phpmd/phpmd#427]
Hi,

We get the following fatal error when executing phpmd:
Fatal error: Can't inherit abstract function PHPMD\Rule::apply() (previously declared abstract in PHPMD\AbstractRule) in /home/viorel.gheba/eis/ieis/vendor/phpmd/phpmd/src/main/php/PHPMD/AbstractRule.php on line 54

We use phpmd 2.4.2 on CentOS 6 with php 5.3.3.

**Comment by ravage84** [comment]
If I get that right, it's a problem with your PHP version:

http://stackoverflow.com/questions/17525620/php-fatal-error-cant-inherit-abstract-function

Try to upgrade to a more recent (still stupported) version of PHP, if you can.
