### ISSUE TITLE
static using private method

### ISSUE THREAD

**Issue by roukmoute** [phpmd/phpmd#432]
Hi!

I think I have a bug about the rule `UnusedPrivateField` with creating a class with `static` word.

Here is an example:

```php
<?php

class Foo
{
    private $timestamp;

    private function __construct()
    {
    }

    public static function fromTimestamp($timestamp)
    {
        $position = new static();
        $position->timestamp = $position->toISO8601($timestamp);

        return $position;
    }

    public function getTimestamp()
    {
        return $this->timestamp;
    }
    
    private function toISO8601(\DateTime $dateTime)
    {
        return $dateTime->format(\DateTime::ISO8601);
    }
}

$foo = Foo::fromTimestamp(1482918535);
```

And here is the error message:

```bash
Foo.php:24	Avoid unused private methods such as 'toISO8601'.
```

I think it's related with https://github.com/phpmd/phpmd/issues/170

**Comment by ravage84** [comment]
Probably more related to #54

And I guess the problem here is the same.
We cannot know what type ``$position`` is of.

Also, this should probably be implemented in pdepend, as PHPMD depends on it for such analysis.
