### ISSUE TITLE
yield keyword

### ISSUE THREAD

**Issue by pmiroslawski** [phpmd/phpmd#438]
I get this when I want to run a phpmd (PHPMD 2.6.0):
Unexpected token: yield from

Generators:
http://php.net/manual/pl/language.generators.syntax.php

**Comment by emirb** [comment]
Addressed in https://github.com/pdepend/pdepend/pull/350

**Comment by tvbeek** [comment]
@pmiroslawski did you run it with the phar file or the composer package?

**Comment by kylekatarnls** [comment]
I can't reproduce either, as pdepend/pdepend#350 was merged, this was probably fixed since.
