### ISSUE TITLE
Make rules extendable

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#44]
I would like to extend some of the rules, like UnusedLocalVariable and others without resorting to copy and paste. It would be much easier if those classes had protected methods instead of private methods. That way I can implement a specific ruleset for my projects, but still get any bug fixes or enhancements to those rules as they become available.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/9355955']

**Comment by kylekatarnls** [comment]
`protected` could be the default. And as I'm browsing private rule methods, I find some duplicates like the getExceptionsList. If those methods would be in the AbstractRule, it would help to create new rules too.

But passing methods to `protected` would be a good start.
