### ISSUE TITLE
Supress Warning on function

### ISSUE THREAD

**Issue by wilcorrea** [phpmd/phpmd#441]
Hey guys, I am adding @SuppressWarnings in a function and is not working. 

Sugestions to workaround?

Can I add that exception in xml? If yes, where can I see about?

-----
Editor
![Editor](https://snag.gy/fj5SYi.jpg)

-----
Terminal
![Terminal](https://snag.gy/7veJVc.jpg)

**Comment by ravage84** [comment]
Hi @wilcorrea 

Can you try it with ``@SuppressWarnings(PHPMD.CyclomaticComplexity)``, please?

Thanks

**Comment by wilcorrea** [comment]
@ravage84 thanks for response!

The version of phpmd.phar here is PHPMD 2.6.0 and after change and re-inspect the source the same warning is shown.

![image](https://cloud.githubusercontent.com/assets/803733/23022771/b905dadc-f439-11e6-8e61-ad954c7cb169.png)

**Comment by wilcorrea** [comment]
I did a simple test right now and removed the `if (function_exists)` above the function declaration and the suppress did work.

Can it be a limitation of the tool?

**Comment by ravage84** [comment]
@wilcorrea thanks for your feedback.

I'm not sure if it's a limitation.
Could you inspect this file using your current PHPMD settings but through the CLI isntead of using it through PhpStorm?

**Comment by wilcorrea** [comment]
Here is the output @ravage84
```xml
<violation beginline="125" endline="151" rule="CyclomaticComplexity" ruleset="Code Size Rules" package="+global" externalInfoUrl="http://phpmd.org/rules/codesize.html#cyclomaticcomplexity" function="out" priority="3">
      The function out() has a Cyclomatic Complexity of 10. The configured cyclomatic complexity threshold is 10.
</violation>
```
Well, thanks a lot for attention! 

I will fix the functions what are under a test if there is another created with same name. The suppress annotation is not being read in that situation and how is this file is my bootstraping I will need see about the impacts of remove the if ; )
