### ISSUE TITLE
UnusedLocalVariable test fails to detect compound variables within a string

### ISSUE THREAD

**Issue by john-whitley** [phpmd/phpmd#442]
Hi,

Thank you for phpmd - it's an awesome tool!

I think we have found a use case that phpmd fails to detect a valid use of a variable when the variable is used only as a compound variable within a string.

```php
public function testRuleDoesApplyToCompoundVariableInString()
    {
        $bar = 'foo';
        return "${bar}_me";
    }
```

At our company we would prefer to use compound variables within a string (e.g. `"${bar}_me"`), rather than string concatenation (e.g. `$bar . '_me'`) and it would be nice to be able to rely on phpmd to detect these uses as legitimate variables, rather than unused variables.

Thanks so much for your time,

**Comment by ravage84** [comment]
Clsoging as related PR has been merged
