### ISSUE TITLE
@SuppressWarnings does not work if the class is within an if statement

### ISSUE THREAD

**Issue by JoryHogeveen** [phpmd/phpmd#444]
I'm using CodeClimate to check my code and I've added a `@SuppressWarnings` to one of my classes that is wrapped in an `if` statement (`class_exists()`).
This if statement causes the warnings to be displayed anyway.

**Comment by ravage84** [comment]
Same as #441

**Comment by JoryHogeveen** [comment]
Ah, yeah correct!
