### ISSUE TITLE
Add rule for the C.R.A.P. Index

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#45]
Short description
-----------------

It would be nice to provide a rule that checks the C.R.A.P. Index[1] of methods and functions and reports those artifacts with critical values.

[1] http://www.artima.com/weblogs/viewpost.jsp?thread=210575

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/9355967']

**Comment by ravage84** [comment]
@manuelpichler reopen this if you stronlgy feel about this feature but I don't really see it.
