### ISSUE TITLE
declaring method return type as "void" increases number of dependencies

### ISSUE THREAD

**Issue by pawel-baster** [phpmd/phpmd#464]
How to reproduce:
1) Use phpmd with CouplingBetweenObjects rule to analyse a file containing:
`public function setPublishDate(DateTime $publishDate) { ... }`
2) repeat after changing method declaration to include void return type:
`public function setPublishDate(DateTime $publishDate) : void { ... }`

Expected behaviour:
Coupling between objects value is the same for both versions of the file.

Actual behaviour:
Declaring `void` as return type increases number of dependencies by one.

Tested with phpmd v. 2.6.0

**Comment by ravage84** [comment]
@manuelpichler I guess this needs to be fixed in pdepend...

**Comment by dakorpar** [comment]
any news?
