### ISSUE TITLE
Unexpected token error calling invokable property

### ISSUE THREAD

**Issue by Garbee** [phpmd/phpmd#465]
**Version**: `2.6.0`

PHPMD currently throws an "unexpected token" exception when you are calling an invokable object that is a property of a class. In the sample files below, the error is thrown from the `index` method of the `Controller` class where the call is being made. It seems to be because the syntax isn't being handled properly within PHPMD. Other tooling such as PHPStan, PHPStorm, and PHP  CS don't see a token problem and the code executes properly within PHP itself.

<details>
<summary>InjectedThing.php</summary>

```php
<?php

namespace App;

class InjectedThing {
    public function __invoke(string $name, string $place): void
    {
        echo "Hello $place, $name";
    }
}
```

</details>

<details>
<summary>Controller.php</summary>

```php
<?php

namespace App;

class Controller
{
    /** @var \App\InjectedThing $thing */
    private $thing;

    public function __construct()
    {
        $this->thing = new InjectedThing();
    }

    public function index(): void
    {
        ($this->thing)('Garbee', 'Universe');
     }
}
```

</details>

**Comment by ravage84** [comment]
Probably a bug in [Pdepend](https://github.com/pdepend/pdepend), please report the bug there.

**Comment by Garbee** [comment]
Didn't see an existing issue or anything close to this syntax for one. Opened [issue 301](https://github.com/pdepend/pdepend/issues/301) there. Thank you!

**Comment by kylekatarnls** [comment]
Will be fixed in the next version of PDepend thanks to @Nacoma https://github.com/pdepend/pdepend/pull/381
