### ISSUE TITLE
Bug: wrongly calculated children count

### ISSUE THREAD

**Issue by dakorpar** [phpmd/phpmd#468]
My build on circleci is failing because:

`/home/ubuntu/project/app/Modules/Api/Responses/Response.php:5	The class Response has 12 children. Consider to rebalance this class hierarchy to keep number of children under 10.`

and this is /home/ubuntu/project/app/Modules/Api/Responses/Response.php:
```
<?php
namespace Project\Modules\Api\Responses;


class Response
{

	/**
	 * @var bool
	 */
	public $success = TRUE;

}
```

**Comment by dakorpar** [comment]
I've figured out what the problem is...
I believe phpmd ignores namespaces and uses just class name and since I have multiple classes with same name in different namespaces phpmd shows full sum and displays error...

**Comment by ravage84** [comment]
@dakorpar thanks for coming back to this.
Could you produce a mimimal reproducable test environment to verify this?

@manuelpichler could this be something in Pdepend?

**Comment by dakorpar** [comment]
I missunterstood this rule. This rule says how many classes are extending current class and not number of properties and methods in it? Right?
