### ISSUE TITLE
Put down Support for HHVM

### ISSUE THREAD

**Issue by ravage84** [phpmd/phpmd#473]
In the recent weeks the PHP community actively talked about stopping to support HHVM for various reasons.

https://derickrethans.nl/mongodb-hhvm.html
https://twitter.com/s_bergmann/status/867338003567521792
https://twitter.com/symfony/status/866920469198512128
https://twitter.com/fabpot/status/865263458903875584
https://twitter.com/lcobucci/status/865081210128793601
https://github.com/doctrine/doctrine2/issues/6424
https://github.com/tideways/php-profiler-extension/issues/30
https://github.com/joomla/joomla-cms/pull/16232
https://github.com/cakephp/cakephp/issues/10674

Since we do not have a high demand on its support I propose to drop support for HHVM.

/cc @manuelpichler

**Comment by ravage84** [comment]
Related https://github.com/phpmd/phpmd/pull/472#issuecomment-305482605

**Comment by eeree** [comment]
I'm in. It will fix TravisCI issues project has right now.

**Comment by ravage84** [comment]
Merged the PR, as the build failures were getting on my nerves.

**Comment by kylekatarnls** [comment]
HHVM is officially abandoned from PHPMD supported PHP versions.
