### ISSUE TITLE
Foreach: UnusedLocalVariable $value

### ISSUE THREAD

**Issue by manuelpichler** [phpmd/phpmd#48]
Hi,

I'm getting error (Avoid unused local variables such as '$value'.) on this kind of code.

foreach($array as $key => $value)
{
    doSomething($key);
}

I think this is a bug
1.  this is the fastest way to do iteration
2. I can't just remove $value since it is a part of language construction.
Sure I could use array_keys($array) but I'm not have to since it is slower.

[Synced from PivotalTracker: 'http://www.pivotaltracker.com/story/show/29579395']

**Comment by BentCoder** [comment]
This is my build.xml block.

```
    <target name="phpmd" description="Mess detection ...">
        <phpmd>
            <fileset refid="src-files"/>
            <formatter type="xml" outfile="build/report/phpmd.xml"/>
        </phpmd>
    </target>
```

I have the changes from https://github.com/phpmd/phpmd/pull/198 as I'm using `phpmd/phpmd 2.2.3` 5eeb5a4d39c8304910b33ae49f8813905346cc35 however my phpmd.xml still contains plenty of `UnusedFormalParameter` violations.

Am I missing something here?

**Comment by JacobBrownAustin** [comment]
It's sad that there's still no good solution to this issue 12 years later.

**Comment by kylekatarnls** [comment]
IMO `allow-unused-foreach-variables` is a good solution. Those who prefer use the `$_` placeholder can just also whitelist this as an exception, so we actually have already 2 way to handle it properly.

Please elaborate on the behavior you would expect.
