### ISSUE TITLE
Can't load external class

### ISSUE THREAD

**Issue by MacSim75** [phpmd/phpmd#498]
I'm writing a custom rulesets for a Drupal 8 project in which I'd like to check if vars & params are in snake_case instead of camelCase.

On that project, PHPMD is added via composer and our /vendor repository has been gitignored.
That means I am not able to add anything new in this PHPMD directory.

Well so my files are in another directory and it seems that PHPMD is not able to autoload these classes:

> Cannot load source file for class: snpphpmd\Rule\SnpControversial\SnpSnakeCaseParameterName.php

Any advice would be appreciated !

![screenshot](https://user-images.githubusercontent.com/5681231/27597491-c8cdfbe4-5b62-11e7-8895-982d67097194.png)

**Comment by ravage84** [comment]
> On that project, PHPMD is added via composer and our /vendor repository has been gitignored.
That means I am not able to add anything new in this PHPMD directory.

It is perfectly fine not add anything to your vendor folder yourself.

Have you setup the autoloading in your project correctly by a) setting all necessary project specific namespaces and files in your composer.json and b) included Composer's autoloader?

https://getcomposer.org/doc/04-schema.md#autoload

**Comment by MacSim75** [comment]
Thank you really much @ravage84 
I obviously forget to manage my namespace in my composer.json autoload section...
Problem solved !

`"autoload-dev": {
    "psr-4": {
      "snpphpmd\\": "scripts/snpphpmd/src/php"
    }
  }`
