### ISSUE TITLE
pdepend + php 7.2 = Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by SailorMax** [phpmd/phpmd#501]
pdepend project is not very active, but your project use it => inform you about this problem:
https://github.com/pdepend/pdepend/issues/310

**Comment by ravage84** [comment]
Thank you. Must be resolved upstream.

**Comment by SailorMax** [comment]
@ravage84 
at PDepend this problem marked as fixed. Can you rebuild phar-file? I can't find anywhere how to do it myself. :/

thank you.

**Comment by JoyceBabu** [comment]
@ravage84 Can you please create a point release fixing this?
