### ISSUE TITLE
 Uncaught Error: Call to undefined function PHPMD\simplexml_load_string() in phar:///usr/bin/phpmd/src/main/php/PHPMD/RuleSetFactory.php:551

### ISSUE THREAD

**Issue by guoyu07** [phpmd/phpmd#508]
1.PHPMD version 2.6.0
2.issue
PHP Mess Detector
phpmd: PHP Fatal error:  Uncaught Error: Call to undefined function PHPMD\simplexml_load_string() in phar:///usr/bin/phpmd/src/main/php/PHPMD/RuleSetFactory.php:551
Stack trace:
#0 phar:///usr/bin/phpmd/src/main/php/PHPMD/PHPMD.php(208): PHPMD\RuleSetFactory->getIgnorePattern('codesize,contro...')
#1 phar:///usr/bin/phpmd/src/main/php/PHPMD/TextUI/Command.php(132): PHPMD\PHPMD->processFiles('/tmp/phpmd_temp...', 'codesize,contro...', Array, Object(PHPMD\RuleSetFactory))
#2 phar:///usr/bin/phpmd/src/main/php/PHPMD/TextUI/Command.php(173): PHPMD\TextUI\Command->run(Object(PHPMD\TextUI\CommandLineOptions), Object(PHPMD\RuleSetFactory))

**Comment by ravage84** [comment]
Hello, thanks for reporting.

Most likely, you have [not loaded the PHP XML extension](http://ch1.php.net/manual/en/simplexml.installation.php), as ``simplexml_load_string()`` is [part of that extension](http://ch1.php.net/manual/en/function.simplexml-load-string.php).

**Comment by tvbeek** [comment]
@guoyu07 can you confirm that you missed the PHP extension?

**Comment by kylekatarnls** [comment]
@guoyu07 We will assume the extension missed. But if not, let us know and I will re-open.
