### ISSUE TITLE
Change exit code when ParserException ?

### ISSUE THREAD

**Issue by roukmoute** [phpmd/phpmd#514]
Actually many people have already reported problems with PHP 7.1.
Me too I've actually theses problems.

But I think the exit code must be 1, like describe in your [documentation](https://phpmd.org/documentation/index.html#exit-codes).

Here it is on this [line](https://github.com/phpmd/phpmd/blob/6adb91f7d574bf2c8a8f8bba53bdd37fa2d8d544/src/main/php/PHPMD/Parser.php#L97-L99), it add errors but it is not catches [here](https://github.com/phpmd/phpmd/blob/6adb91f7d574bf2c8a8f8bba53bdd37fa2d8d544/src/main/php/PHPMD/TextUI/Command.php#L107) for return 1.

So CircleCI returns that all right, and in fact, it is not.
Yes it is a temporary problem until you update library, but I think it will be a good things if we have a wrong exit code to see them.

**Comment by tvbeek** [comment]
Good  point, it is a problem in the Command and PHPMD classes that don't check if we have any error.
