### ISSUE TITLE
Malformed table in DevelopmentCodeFragment doc

### ISSUE THREAD

**Issue by SrihariThalla** [phpmd/phpmd#520]
Hi,

The [Design Rules](https://phpmd.org/rules/design.html) doc has an error under `DevelopmentCodeFragment` table.

```
Malformed table. Text in column margin in table line 4.
```

Regards!

**Comment by ravage84** [comment]
True, are you willing to create a PR that fixes that? ([Hacktoberfest](https://hacktoberfest.digitalocean.com/), eh?)?

**Comment by tariq86** [comment]
I submitted pull request #570 to fix this

**Comment by kylekatarnls** [comment]
Fixed in 2.8.0
