### ISSUE TITLE
Feature Request: Support for phive

### ISSUE THREAD

**Issue by ChristianSchaefer** [phpmd/phpmd#521]
Can you please provide phpmd for install with phive?

**Comment by ravage84** [comment]
I'm open to that. Would you be willing to contribute a PR for that ([Hacktoberfest](https://hacktoberfest.digitalocean.com/), eh?)?

**Comment by steffenbrand** [comment]
Seems like a phar is already being build and is attached tot he releases.
But `phive install phpmd/phpmd` fails.

```
Phive 0.13.0-8-gc00c18f - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/phpmd/phpmd/releases
[WARNING]  phpmd/phpmd 2.7.0: No GPG Signature 
[WARNING]  phpmd/phpmd 2.6.1: No GPG Signature 
[ERROR]    No matching release found!
```

This links says, that a valid pgp signature file would enable the phive installation:
https://phar.io/distribute-your-own.html

This link explains how to do it:
https://phar.io/howto/sign-and-upload-to-github.html

Generating, registering and attaching the file to a release does not sound like something any contributor can do :) Or am I wrong?
And manually attaching the .asc to every release sounds like something that should be automated somehow. But I don't know how.

I would really like to see this feature, because we want to use phive to manage our CI tools.
But I'm not sure how I can help.

**Comment by kylekatarnls** [comment]
This has to be done in the Travis-CI release process. The phar is built here:
https://github.com/phpmd/phpmd/blob/master/.travis.yml#L64

So this feature can be submitted as a pull-request.

**Comment by steffenbrand** [comment]
Ok, I will try my best, but I'm not an experienced Travis user and I don't know how to instrument it properly.

Is there already a GPG key for phpmd that is registered with the keyserver?
And is `gpg`and the key available in the travis build?
If so, what's the email to use?

I would try to sign the phar like `gpg -u dunno@phpmd.org --detach-sign --output phpmd.phar.asc phpmd.phar`.

If `gpg` or the key aren't available, it would result in:
```
gpg: skipped "dunno@phpmd.org": No secret key
gpg: signing failed: No secret key
```

**Comment by kylekatarnls** [comment]
I will try my key.

**Comment by temp** [comment]
Can't you upload the key? phpmd can't be installed via phive for days now...

**Comment by tvbeek** [comment]
> 
> 
> Can't you upload the key? phpmd can't be installed via phive for days now...

It was never possible so it wasn't only not possible for days 😉 

But I believe we need to have some patience because @ravage84 managed the key and is currently not available.

**Comment by theseer** [comment]
Given that at least the current 2.7.0 release has a `.phar` and its matching `.phar.asc` available, the key used for signing is available on keyservers, the installation works just fine and technically this ticket could be closed.

Some minor things:
- You can register an alias - so installation works via `phive install phpmd` for instance. Simply supply a PR against the [phar.io's repository file](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml)

- You might want to consider publishing key details (fingerprint, id, ...) on phpmd.org so users can double check if they want to trust the key before importing it

- Update the docs ;-)

**Comment by ravage84** [comment]
@theseer 

> You can register an alias - so installation works via phive install phpmd for instance. Simply supply a PR against phar.io's repository file

Done so in https://github.com/phar-io/phar.io/pull/70

**Comment by ravage84** [comment]
@theseer 

> You might want to consider publishing key details (fingerprint, id, ...) on phpmd.org so users can double check if they want to trust the key before importing it

Do you have a good example for that? Better we imitate some good example than to reinvent it badly.

**Comment by ravage84** [comment]
Created an issue for adding the new installation option: https://github.com/phpmd/phpmd/issues/701

@kylekatarnls do you think our setup will work on future releases? If so, we can close this issue.

**Comment by kylekatarnls** [comment]
We will respect semver and you GitHub release so it's now the responsibility of Phive to ensure it properly downloads the higher stable version. So I close :)

**Comment by theseer** [comment]
> @theseer
> 
> > You might want to consider publishing key details (fingerprint, id, ...) on phpmd.org so users can double check if they want to trust the key before importing it
> 
> Do you have a good example for that? Better we imitate some good example than to reinvent it badly.

A common (maybe best?) practice for publishing key IDs and fingerprints is the regular project website. For instance, we publish our ID and fingerprint in the footer of our website (https://phar.io). You can then simply refer to it at the installation docs so people have a means to look it up.

If you want to go real fancy, you can adopt the phar verification documentation that @sebastianbergmann wrote for `PHPUnit` (https://phpunit.readthedocs.io/en/latest/installation.html#verifying-phpunit-phar-releases) - then people could make use of the GPG signature even if they do not want to use, can't use or merely don't trust PHIVE.
