### ISSUE TITLE
Error with "design" rule

### ISSUE THREAD

**Issue by filipesperandio** [phpmd/phpmd#522]
Error: `PHP Notice:  Trying to get property of non-object in .../phpmd/src/main/php/PHPMD/RuleSetFactory.php on line 556`

Command: `phpmd /code_dir text design`

It happens when analyzing this project: https://github.com/supernova-ws/SuperNova

**Comment by ravage84** [comment]
@filipesperandio thanks for reporting. Can you help dig deeper?

**Comment by ravage84** [comment]
MIght be connected to https://github.com/phpmd/phpmd/issues/517

**Comment by ravage84** [comment]
Might be due to https://github.com/phpmd/phpmd/issues/520

**Comment by filipesperandio** [comment]
@ravage84 How can I help?

**Comment by ravage84** [comment]
It would be great if you could pin down the offending code by extracting a reproducable environment. For example the minimalistic code necessary to trigger the problem.

**Comment by tvbeek** [comment]
@filipesperandio can you add some code to show how this behavior is created?

**Comment by filipesperandio** [comment]
Gosh, this is an old one.
I was working at integrating this with CodeClimate and haven't came back here since then, so I barely recall what this was about.

I assume we can reproduce the problem with the explanation in the description.
If I recall, I was expecting it to warn or generate a violation, but instead it was breaking with an error.
If this is not reproducible anymore I am glad to just close it.

**Comment by kylekatarnls** [comment]
Hi @filipesperandio. I close this for now, but if you can reproduce it, let us now and I will re-open.
