### ISSUE TITLE
LongVariable rule should apply on private variables

### ISSUE THREAD

**Issue by duncancumming** [phpmd/phpmd#527]
Currently the LongVariable rule skips private variables:
https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/Rule/Naming/LongVariable.php#L55

The ShortVariable rule doesn't do the same.
https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/Rule/Naming/ShortVariable.php#L54

This isn't documented.  Can we get rid of this?

**Comment by adamcameron** [comment]
I could not agree more. We still need to read private variable names just as much as the public / protected ones.

**Comment by ravage84** [comment]
Refers change from: https://github.com/phpmd/phpmd/issues/16

**Comment by ravage84** [comment]
@duncancumming and @adamcameron  are you interested in putting up a PR for making this a configurable as I mentioned in [my comment](https://github.com/phpmd/phpmd/issues/16#issuecomment-58387822)? ([Hacktoberfest](https://hacktoberfest.digitalocean.com/), anybody?

**Comment by adamcameron** [comment]
Yeah Dunc and I (who are colleagues) were discussing this. We didn't want to charge in and make pull reqs just cos we felt like stuff ought to be different without getting a nod from the stewards of the app though.

Also... never made a pull req to this project. you got some dev guidelines or something we ought to eyeball first? We'd also need to get it cleared with our boss, but that shouldn't be too hard.

**Comment by ravage84** [comment]
We are soemwhat light on guidelines, but take this for starters:
https://github.com/phpmd/phpmd/blob/master/CONTRIBUTING.md

Also, have a look at similar PRs:
https://github.com/phpmd/phpmd/pull/159
https://github.com/phpmd/phpmd/pull/197
https://github.com/phpmd/phpmd/pull/198

If you still have trouble, write me via email or Skype (same ID).

**Comment by adamcameron** [comment]
OK, I've run it up the flagpole at work. Will revert shortly.
