### ISSUE TITLE
Missed php-includepath delcaration in ruleset_xml_schema.xsd 

### ISSUE THREAD

**Issue by vkublytskyi** [phpmd/phpmd#546]
## An issue

[The actual implementation](https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/RuleSetFactory.php#L196) of `\PHPMD\RuleSetFactory` allows declaring `php-includepath` to provide possibility to explore and use rulesets defined in 3rd party libraries. However, http://pmd.sourceforge.net/ruleset_xml_schema.xsd does not declare `php-includepath` so its usage makes ruleset file declaration invalid.

## Additional Information

`\PHPMD\RuleSetFactory::filePaths` [returns](https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/RuleSetFactory.php#L542) a possible locations list of referenced ruleset. The algorithm searches in PHPMD installation folder, then in a current working directory (in most cases that would be projected directory),  and then in all folders from include paths. So, if some project would like to use rulesets provided by 3rd party library, a path to the library should be added to include paths. It is not a requirement of PHP code as autoloading mechanism may not require modification of include paths. Because of this, the best place to declare modification of include paths is a projects ruleset file.

## Related issue
- phpmd/phpmd#545
- magento/magento2#13400

## Proposed solution
@addiks in phpmd/phpmd#545 provided an [updated XSD](https://gist.github.com/addiks/b5f015e833634b5bccacfc0f4699d7d5) file that needs to be deployed to http://pmd.sf.net/ruleset_xml_schema.xsd

**Comment by ravage84** [comment]
> http://pmd.sf.net/

This is not PHP Mess Detector's but Java's Mess Detector's (the original) Website.

**Comment by kylekatarnls** [comment]
So it also requires us to extends **ruleset_xml_schema.xsd** and publish our own xsd file for PHPMD ruleset format.
