### ISSUE TITLE
Broken phar file

### ISSUE THREAD

**Issue by ghost** [phpmd/phpmd#551]
Where can i get phpmd.phar file ?

 issue "SHA512 signature could not be verified: broken signature in C:\php\phpmd.phar:8" is still presented in http://static.phpmd.org/php/latest/phpmd.phar

**Comment by jakzal** [comment]
Until we fix it in this repo, the phar can be downloaded from here: https://github.com/jakzal/phpmd/releases/download/2.6.0-jakzal-3/phpmd.phar

**Comment by ravage84** [comment]
@jakzal what is necessary to fix it in this repo?

**Comment by jakzal** [comment]
@ravage84 I have a PR ready. We'd only need to drop <PHP7.1 support as this is what any maintained version of box supports.

**Comment by ravage84** [comment]
Can you please create the PR, so we can talk about it there?

**Comment by ravage84** [comment]
Thanks to @jakzal's efforts, we have a new [PHAR file](https://github.com/phpmd/phpmd/releases/download/2.6.1/phpmd.phar) available, attached to the related tag/release [2.6.1](https://github.com/phpmd/phpmd/releases/tag/2.6.1).

**Comment by kylekatarnls** [comment]
As the phar works, I close this issue. 🚀
