### ISSUE TITLE
ElseExpression explanation needs an update

### ISSUE THREAD

**Issue by sanmai** [phpmd/phpmd#560]
[Currently it says:](https://phpmd.org/rules/cleancode.html#elseexpression)

> An if expression with an else branch is never necessary. 

True, this proposition is correct in most cases. But there are cases, especially in generators, where `else` is unavoidable. Here's a primer:
```php
$example = [
    [1, 1, 1],
    2,
];

var_dump(iterator_to_array((function () use($example) {
    foreach ($example as $element) {
        if (is_array($element)) {
            yield from $element;
        } else {
            yield $element;
        }
    }
})()));


var_dump(iterator_to_array((function () use($example) {
    foreach ($example as $element) {
        if (is_array($element)) {
            yield from $element;
            return;
        }
        // Notice no else here

        yield $element;
    }
})()));
```
[If you would run this primer](https://3v4l.org/6hoqq), you would see that these two snippets give different results:
```
array(3) {
  [0]=>
  int(2)
  [1]=>
  int(1)
  [2]=>
  int(1)
}
array(3) {
  [0]=>
  int(1)
  [1]=>
  int(1)
  [2]=>
  int(1)
}
```

Possible solution would be to update the documentation to either read:

> An if expression with an else branch is *almost* never necessary.

Or to update the rule to ignore `else` in generators.

**Comment by fuzzy76** [comment]
I would argue that having rules that cannot be avoided in all cases is stupid. :( Or it could be my OCD that kicks in when I have codebases that will always have warnings unless I convolute my code. Though #288  doesn't give my any hope.

**Comment by kylekatarnls** [comment]
> True, this proposition is correct in most cases. But there are cases, especially in generators, where else is unavoidable
Not unavoidable, you just need to replace `return` with `continue` in your example to get the same output without using `else`.

**Comment by sanmai** [comment]
All right then, let me think of another example.

**Comment by sanmai** [comment]
Half a hour later I still can't think of any. So I guess you're right. Thanks for the wisdom, 
@kylekatarnls.

Closing for now.
