### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nenad** [phpmd/phpmd#568]
It's been some time since a new release of this tool has been pushed.

**Comment by echernyavskiy** [comment]
any chance 2.6.1 or 2.7.0 would be tagged soon?

**Comment by andreasschroth** [comment]
That's the reason why I removed it from our CI pipeline now - no new releases means no progress and there are other PHP analysis tools out there that are actively developed. Please don't get me wrong, I appreciate your effort a lot for maintaining / developing phpmd, but just wanted to give some feedback. I think regular releases (at least twice a year) and keeping up with the PHP language developments are essential.

**Comment by ravage84** [comment]
New releases are comming soon.
