### ISSUE TITLE
How to set custom phpmd coding standard ruleset in Netbeans 8.1?

### ISSUE THREAD

**Issue by HemaliSavaliya** [phpmd/phpmd#581]
I install phpmd in netbeans 8.1 and it shows me errors of my code according to phpmd all rules but what if 
I want to apply some of the rules on current file for that I make one custom coding standard xml  file  and it works fine as I run it through command line but I don't know how to set it with netbeans 8.1?

**Comment by ravage84** [comment]
Since I do not use Netbeans, I cannot help you.

Please refer to the help & community resources of NetBeans.
