### ISSUE TITLE
Checking for php 7 features

### ISSUE THREAD

**Issue by sergeynezbritskiy** [phpmd/phpmd#586]
Hello guys. Is it possible to check with phpmd, that my code follows php7 standards. e.g. declaration "strict_types=1" exists, every argument in method has type hint, every method has return type specified etc ?
Thanks

**Comment by mvanduijker** [comment]
You can use the extra PHPCS rules from https://github.com/slevomat/coding-standard for that.

**Comment by ravage84** [comment]
@sergeynezbritskiy depending on what exactly you want to check, a style checker could be more appropriate. Please, provide examples of what you want to check, if you haven't found any other tool, yet.
