### ISSUE TITLE
Wrong property names in design.xml rules

### ISSUE THREAD

**Issue by ruimelodev** [phpmd/phpmd#588]
The properties for `NumberOfChildren`, `DepthOfInheritance` and `CouplingBetweenObjects` have the name `minimum` but then they're referred to the maximum in the description tag.

Example:
```
rule name="CouplingBetweenObjects"
<property name="minimum" value="13" description="Maximum number of acceptable dependencies." />
```

It should be:
```
<property name="maximum" value="13" description="Maximum number of acceptable dependencies." />
```

**Comment by kylekatarnls** [comment]
Let's track this rather in #670 which has a more complete list.

For the record, the ambiguity comes from "maximum allowed" = "minimum before raising the rule violation" so from the rule violation point of view, *minimum* make sense, but indeed, all names should rather be harmonized to end-user point of view.
