### ISSUE TITLE
Support for Symmetric array destructuring

### ISSUE THREAD

**Issue by kiler129** [phpmd/phpmd#589]
I discovered that PHPMD chokes on `foreach($it as [$a, $b])` construction. It seems like support for [this type of array destructuring](https://secure.php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring) is not implemented.

Is there any chance for implementation?

**Comment by dehrk** [comment]
I'm also getting "parser has reached an invalid state" for syntax like `[, $name] = $matches;`

**Comment by kiler129** [comment]
We finally switched to PhpStan since the functionality is just so much more extensive.

**Comment by kylekatarnls** [comment]
It will be fixed soon: https://github.com/pdepend/pdepend/pull/383
