### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by edhgoose** [phpmd/phpmd#603]
The phpmd.org site is down at the moment. 

Apologies if you're already aware!

**Comment by viion** [comment]
Been down all morning

**Comment by matrunchyk** [comment]
I had to remove the package from my Docker container because of this problem, it's affecting our business..

**Comment by chilimatic** [comment]
here too. Maybe adding another mirror for this would help? I will removed the dependency for the moment. On the other hand I probably will just create my own dummy mirror to reduce the load on your system .... :)

**Comment by jakzal** [comment]
@chilimatic that is what i've done for pdepend, and it looks like my changes will be also merged to upstream. Encourage you to do the same :)

@matrunchyk you get the support you're paying for. What could you do to help?

**Comment by jakzal** [comment]
Until it's fixed in this repo, feel free to use phar I built in mine. It's published with github releases: https://github.com/jakzal/phpmd/releases/tag/2.6.0-jakzal-2

Only PHP 7.1-7.3 is supported.

**Comment by paul-gene** [comment]
Site still down. Any update?

**Comment by tvbeek** [comment]
I send an email to @manuelpichler and @ravage84 to offer help with the hosting but didn't get any response yet. So we have to wait.

**Comment by ravage84** [comment]
Hi @tvbeek 

Thank you for reaching out. Unfortunately, only @manuelpichler has the necessary access and knowledge.

**Comment by tvbeek** [comment]
@ravage84 thanks for the feedback, I see that phpmd.org is hosted on the same ip as @manuelpichler his website. I hope that he received the mail and is able to respond.

**Comment by manuelpichler** [comment]
Hello together,
sorry but where my personal website and phpmd.org or pdepend.org were
hosted was shutdown by the ISP, because it was a too old instance.
Currently and in future I have no time to restore anything, but I am
willing to sponsor the domains and configure the DNS, so that some one
else can host the project website.
Kind regards  Manuel
Btw. same applies to any kind of project maintenance 
Am Freitag, den 17.05.2019, 08:35 -0700 schrieb Tobias van Beek:

**Comment by macwinnie** [comment]
> Hello together, sorry but where my personal website and phpmd.org or pdepend.org were hosted was shutdown by the ISP, because it was a too old instance. Currently and in future I have no time to restore anything, but I am willing to sponsor the domains and configure the DNS, so that some one else can host the project website. Kind regards Manuel Btw. same applies to any kind of project maintenance

Hi @manuelpichler,
what do you think about restructuring the project for using GitHub-Infrastructure (GitHub Pages or even the Wiki)? Or thinking about Uberspace with kind of croudfunding, i.e.?
There could be great possibilities =)

**Comment by tvbeek** [comment]
@manuelpichler Do you have the source code of phpmd.org available? If yes can you send / transfer it to me? (Email is visible on my profile) then I will create a place where it will be hosted and send you the ip addresses. It will be a fast way to put it back online and after that it can be a good idea to look to the solution from @macwinnie and found out who are willing and have the time to maintain the project.

**Comment by ravage84** [comment]
@tvbeek the sorce of the site is actually just the source and it's located in this repo at https://github.com/phpmd/phpmd/tree/42bf8ad43793e7b77c0c8681a1eabaf48b69bcf7/src/site

Going forward, I support the idea of using a more modern & well understood documentation approach.

**Comment by fritz-cwp** [comment]
Since others might run into the same issue as me - wanting the phar executable and not being able to download it, and too paranoid to use other people's executables, here's a `Dockerfile` for building the binary yourself with Docker, without polluting your computer environment with a bunch of extra tooling in the process:
```Dockerfile
# ./Dockerfile
FROM frekele/ant:1.10.3-jdk8

RUN apt-get update && apt-get install -y \
  git \
  php7.0 \
  php7.0-common \
  php7.0-cli \
  php7.0-fpm \
  php7.0-mysql \
  php7.0-dev \
  php7.0-mbstring \
  php7.0-zip \
  php7.0-bz2

RUN git clone git://github.com/phpmd/phpmd.git /pharbuild

WORKDIR /pharbuild

RUN git submodule update --init

# Run the Apache Ant build process.
# The `|| true` is to ignore the final bit of the test that fails,
# because the binary still gets created successfully.
# (Add -v here if you need more verbose output)
RUN ant package -D-phar:filename=phpmd.phar || true

CMD ["cp", "phpmd.phar", "/output/phpmd.phar"]
```

Save that as a text file named `Dockerfile` and run the following in the same directory to build the image and the binary:

```sh
docker build -t phpmd-builder .
```

And this to copy it to your current directory:
```sh
docker run --rm -v"$(pwd):/output" phpmd-builder
```

**Comment by tvbeek** [comment]
> @tvbeek the sorce of the site is actually just the source and it's located in this repo at https://github.com/phpmd/phpmd/tree/42bf8ad43793e7b77c0c8681a1eabaf48b69bcf7/src/site

Thanks, I'm trying to get it working but I'm not familiar with rst so I need to dig deeper into it to get the site working.

**Comment by hbaeumer** [comment]
I like the idea to use github pages or wiki.
That would save the cost of a hosting.
Are there anyone interested in maintaining phpmd?
@tvbeek  would not have to take care of hosting and rst.

**Comment by gnovaro** [comment]
> I like the idea to use github pages or wiki.
> That would save the cost of a hosting.
> Are there anyone interested in maintaining phpmd?
> @tvbeek would not have to take care of hosting and rst.

Create repo phpmd.github.io i can give a hand to make this

**Comment by ravage84** [comment]
I officially started the search for a new team of maintaners for PHPMD (& PDepend). If anybody is interested write me an email, see my GitHub profile page.

**Comment by inquiloper** [comment]
It's still down. Any news?

**Comment by ravage84** [comment]
@inquiloper the new team of maintainer has just started discussions. Please be patient with us.

**Comment by tvbeek** [comment]
@ravage84 The merge is done but the dns isn't working yet.

**Comment by ravage84** [comment]
Hello everybody, for the time being a temporary website can be found at https://phpmd.github.io/phpmd/.
It's not fully working, but it's a start.

We will inform you, once there are updates.

**Comment by ravage84** [comment]
Oh, totally forgot to say the PHPMD Website is up and runing again at https://phpmd.org/

**Comment by fritz-c** [comment]
Great news!

Any plans to resurrect the phar download? Right now it mentions http://static.phpmd.org/php/latest/phpmd.phar on the download page, but it could always be moved to the same GitHub Pages site. Or maybe the phar could be added to the releases page on GitHub.

**Comment by ravage84** [comment]
> Any plans to resurrect the phar download? 

@fritz-c yes, we are working on it.

Related issue #551, related PR #613
