### ISSUE TITLE
upgraded, now getting: "Property "ignorepattern" does not exist."

### ISSUE THREAD

**Issue by eeyon** [phpmd/phpmd#647]
upgraded phpmd to latest(3.4.2) using composer and now our tests fail with:
```Property "ignorepattern" does not exist.```
I cant seem to find anything in the changelog dictating what changes i need to make to our configs while upgrading or that there were breaking changes(could have missed it through). 

Any ideas on what changes i need to make or ideas on where to start debugging this to get our tests running again?

**Comment by kylekatarnls** [comment]
Hi @eeyon, 3.4.2 does not exist. Can you show your **phpmd.xml** to see which rule use this property?

**Comment by tvbeek** [comment]
@eeyon I assign this issue to you because we need more input to reconstruct the issue. After that input we can (try to) solve your problem.

**Comment by kylekatarnls** [comment]
I'm closing this as lacking infos. Feel free to complete and I will re-open
