### ISSUE TITLE
Property Lists get merged together on Website

### ISSUE THREAD

**Issue by ravage84** [phpmd/phpmd#650]
In PR #329 a new property "exceptions" was added:
https://github.com/phpmd/phpmd/pull/329/files#diff-79d71ab57c2216abee5b7c50bb4c04f1

It get's merged with the other one, though, on the website:
https://phpmd.org/rules/unusedcode.html#unusedlocalvariable

Same for ShortVariables:
https://phpmd.org/rules/naming.html#shortvariable

**Comment by kylekatarnls** [comment]
I'm looking for the right way to display tables.

We should move on a markdown compiler.

**Comment by kylekatarnls** [comment]
I will probably need to customize the RST parser to handle properly them. But ti will conflicts with #624
