### ISSUE TITLE
Deprecated: implode(): Passing glue string after array is deprecated.

### ISSUE THREAD

**Issue by SailorMax** [phpmd/phpmd#658]
- PHPMD version: 2.7.0
- PHP Version: 7.4.0b2
- Installation type: phar file
- Operating System / Distribution & Version: Windows 10

### Current Behavior
Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in phar://phpmd.phar/src/main/php/PHPMD/RuleSetFactory.php on line 575

### Expected Behavior
no warnings

### Steps To Reproduce:
validate any php-file

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [ ] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by kylekatarnls** [comment]
Confirmed since 7.4.0beta1 (not present in alpha versions).

Thanks for the notice @SailorMax if you want to fix it, we would be glad to merge your PR.

**Comment by SailorMax** [comment]
Thanks, but I leave it to collaborators with pre-installed local infrastructure.
I not ready to spend so much time for so small fix. May be next time :)

**Comment by kylekatarnls** [comment]
For the record, GitHub has online editor https://github.com/phpmd/phpmd/edit/master/src/main/php/PHPMD/RuleSetFactory.php

And all changes will be checked automatically by Travis-CI, and manually reviewed by us, so it's fine to use it for safe small changes.

**Comment by SailorMax** [comment]
Here is my first try of online patch: https://github.com/phpmd/phpmd/pull/659
thanks! :)
