### ISSUE TITLE
Missing class import via use statement for trait with static::class

### ISSUE THREAD

**Issue by cacahouwete** [phpmd/phpmd#674]
- PHPMD version: 2.7.0
- PHP Version: 7.3.9
- Installation type: (composer)
- Operating System / Distribution & Version: (Ubuntu 18.04 => Docker => Debian GNU/Linux 9)

### Current Behavior
/app/src/Traits/EnumTrait.php:16        Missing class import via use statement (line '16', column '32').

### Expected Behavior
I expect that there are no error.

### Steps To Reproduce:
run phpmd on following class:
```php
<?php

declare(strict_types=1);

namespace App\Traits;

trait EnumTrait
{
    public static function validate(string $value): bool
    {
        return \in_array($value, self::getArray(), true);
    }

    public static function getArray(): array
    {
        $reflectionClass = new \ReflectionClass(static::class);

        return $reflectionClass->getConstants();
    }
}
``` 

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by MarkVaughn** [comment]
This doesn't have to do with static::class, more that you are not importing ReflectionClass.
This passes with no error.

```
<?php

declare(strict_types=1);

namespace App\Traits;

use ReflectionClass;

trait EnumTrait
{
    public static function validate(string $value): bool
    {
        return \in_array($value, self::getArray(), true);
    }

    public static function getArray(): array
    {
        $reflectionClass = new ReflectionClass(static::class);

        return $reflectionClass->getConstants();
    }
}

```

**Comment by kylekatarnls** [comment]
Indeed it could be cool to have the name of the class in the message so we know which one is concerned if multiple class names in the same line (counting "column" position is not that easy).

**Comment by tvbeek** [comment]
@cacahouwete can you verify that the ReflectionClass is the problem?
Naming the class in the message is a good addition but a separated issue so I like to close this issue if the ReflectionClass is the problem.

**Comment by kylekatarnls** [comment]
As no feedback received here, I assume it was the missing ReflectionClass fault.
