### ISSUE TITLE
Possible CleanCode/BooleanArgumentFlag.php Bug

### ISSUE THREAD

**Issue by dehrk** [phpmd/phpmd#687]
Should this rule be adding a violation on private methods? If it's only being called from inside the class, wouldn't that mean that responsibility is still "entirely encapsulated by the class"?

**Comment by kylekatarnls** [comment]
Hi, first, please edit your issue to respect the issue pattern (https://github.com/phpmd/phpmd/issues/new?template=1_Bug.md) with missing informations.

Then I don't see a good example that would justify that private method could break this rule. It's about: 1 method serves 1 goal (private methods too).

If you gives a concrete example as suggested in the pattern, we could be able to see if your case is a relevant exception to the rule or a normal case you can improve following the rule.

Thanks,

**Comment by dehrk** [comment]
Thanks for the quick response. I can see your point there, so feel free to close this.
