### ISSUE TITLE
Missing ANSI renderer in version 2.7

### ISSUE THREAD

**Issue by MrSuit** [phpmd/phpmd#702]
- PHPMD version: 2.7.0
- PHP Version: 7.3.0
- Installation type: composer
- Operating System / Distribution & Version: Debian/Buster 10.2

### Current Behavior
After passing as a second parameter ansi it shows me output below.

> Can't find the custom report class: ansi

### Expected Behavior
A command line friendly format

### Steps To Reproduce:
Get version 2.7.0. and run
phpmd ./somedir ansi unusedcode

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by MarkVaughn** [comment]
Hi, 
This PR https://github.com/phpmd/phpmd/pull/595 was landed and is in 2.8 beta release
