### ISSUE TITLE
Version mismatch in the latest released phar file

### ISSUE THREAD

**Issue by rohanvakharia** [phpmd/phpmd#715]
- PHPMD version: 2.8.0
- PHP Version: 7.2.26-1+ubuntu18.04.1+deb.sury.org+1
- Installation type: phar file
- Operating System / Distribution & Version: Ubuntu 18.04.3 LTS

### Current Behavior
`phpmd --version`
`PHPMD 2.7.0snapshot201912240943`

### Expected Behavior
`phpmd --version`
`PHPMD 2.8.0snapshot201912240943`

### Steps To Reproduce:
1. Downloaded phpmd.phar from the link `https://github.com/phpmd/phpmd/releases/download/2.8.0/phpmd.phar`
2. It should show the version 2.8.0 instead of 2.7.0

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by kylekatarnls** [comment]
2.8.1 released with inner version number synchronized. Thanks.
