### ISSUE TITLE
Missing txt docs for rules 

### ISSUE THREAD

**Issue by ale7714** [phpmd/phpmd#717]
## Description

Ale from Code Climate here, we usually use the txt docs to pull down documentation for the rules. For example: http://phpmd.org/rules/cleancode.txt. I just noticed that these links are not longer accessible. Were they moved? or no longer available on txt format?

**Comment by kylekatarnls** [comment]
Hi, indeed we (the new team) reworked the doc generation to use a more simple and easier system to contribute too. But we love your job and will try our best to give you a good API. Is pure text a requirement or would it ve better to have HTML, markdown or RST ?

**Comment by ale7714** [comment]
@kylekatarnls thank you so much for the quick followup! Our script assumes the file is in txt and parses the text following the structure the doc used to have. But we can do the same markdown or rst.

**Comment by kylekatarnls** [comment]
Great, rigth now documentation sources lie in https://github.com/phpmd/phpmd/tree/master/src/site/rst as RST files. So wecould easily copy them and add links.

**Comment by ale7714** [comment]
@kylekatarnls that would definitely do the trick. Thanks!

**Comment by kylekatarnls** [comment]
With #719 website pages will have 2 links to source and modification GitHub pages such as:
Source: https://raw.githubusercontent.com/phpmd/phpmd/master/src/site/rst/rules/cleancode.rst
Edit: https://github.com/phpmd/phpmd/edit/master/src/site/rst/rules/cleancode.rst
And the PR will also make RST files downloable on phpmd.org.

**Comment by ale7714** [comment]
@kylekatarnls thank you! this great news. Happy new year!

**Comment by efueger** [comment]
Hi @kylekatarnls - Emily from Code Climate Support 👋

quick bump on your [PR #719](https://github.com/phpmd/phpmd/pull/719) - it looks like the checks passed, just waiting on the reviews.

Thanks!
