### ISSUE TITLE
Phar for PHPMD 2.8.x has no signature

### ISSUE THREAD

**Issue by theseer** [phpmd/phpmd#723]
The last signed version is 2.7.0, which makes it the default version installed by phive. Maybe you can add signatures to the 2.8.0 and 2.8.1 releases?

**Comment by kylekatarnls** [comment]
We don't want to manually sign every builds so we're working on a way to automate the signing:
#688

**Comment by theseer** [comment]
Understood. Would be nice to have a signature anyhow ;)

But feel free to close this.
