### ISSUE TITLE
Error on PHP 7.4 arrow functions

### ISSUE THREAD

**Issue by Kovalchuk91** [phpmd/phpmd#726]
- PHPMD version: 2.8.1
- PHP Version: 7.4.1
- Installation type: (composer)
- Operating System / Distribution & Version: (Debian GNU/Linux 10)

### Current Behavior
Running phpmd on file that contains PHP 7.4 arrow functions shows an error "Unexpected token: fn"

### Expected Behavior
No error shown.

### Steps to reproduce
1. Create a php script with code that includes arrow function
2. Run phpmd on it

**Comment by kylekatarnls** [comment]
Hi, it will be fixed in the next release of PDepend:
https://github.com/pdepend/pdepend/pull/426
