### ISSUE TITLE
short variable names (exclude if in function signature)

### ISSUE THREAD

**Issue by bkdotcom** [phpmd/phpmd#730]
I would like the option to exclude short variable name warnings if they occur in the function signature..

The thought being that I have PhpDoc comment that defines what the var is

**Comment by kylekatarnls** [comment]
Add a `@SuppressWarnings(PHPMD.ShortVariable)` in the PHPDoc block of the function.
https://phpmd.org/documentation/suppress-warnings.html

In my opinion, this is not a reason enough to use 1/2 letters variable names. It's also about knowing all way long what we are taking about: a real name to remember easily what it is, while the PHPDoc gives a description, not just a name and is mostly for the function "user" explaining what to pass, how to use, it's not supposed to be a legend to map variables names.

**Comment by tvbeek** [comment]
@bkdotcom Can you give feedback if @kylekatarnls did miss a point? Else we will close this issue to get the list a little bit cleaner.
