### ISSUE TITLE
[PHP_7.4] The magic methods __serialize and __unserialize must not be in camelCase

### ISSUE THREAD

**Issue by Zarcox** [phpmd/phpmd#732]
- PHPMD version: 2.8.1
- PHP Version: 7.4.2
- Installation type: Composer
- Operating System / Distribution & Version: Debian 9

### Current Behavior
PHP 7.4 introduced this RFC : [https://wiki.php.net/rfc/custom_object_serialization](https://wiki.php.net/rfc/custom_object_serialization)

But PHPMD reports the following errors :

```
/path/class.php:1	The method __serialize is not named in camelCase.
/path/class.php:2	The method __unserialize is not named in camelCase.
```

### Expected Behavior
The method `__serialize` must not be named in camelCase.

### Steps To Reproduce:
Simply use the following code in a class :

```
    public function __serialize(): array
    {
        return [
            $this->test,
        ];
    }

    public function __unserialize(array $data): void
    {
        [
            $this->test,
        ] = $data;
    }
```

**Comment by kylekatarnls** [comment]
Thanks @Zarcox, they will be allowed in 2.8.2.
