### ISSUE TITLE
Add allow-underscore option

### ISSUE THREAD

**Issue by tuc0w** [phpmd/phpmd#742]
Since CamelCasePropertyName and CamelCaseMethodName already implement the `allow-underscore` and `allow-underscore-test` options it would be consistent to implement this option also for CamelCaseParameterName and CamelCaseVariableName.

It should be a quick addition which I could do in my spare time.

**Comment by tvbeek** [comment]
@tuc0w that sounds like a good addition! We are welcoming your PR for this, I assign this issue to you because you say you could do it in your spare time.
