### ISSUE TITLE
Unreadable error when parsing a file with wrong syntax

### ISSUE THREAD

**Issue by vivekKodira** [phpmd/phpmd#75]
Raising on behalf of the CloudMunch team. 

The file being parsed by PHPMD had the following line:

"include = DIRECTORYPATH.'/Document/SomeFile.php';"

(syntax error is the equals sign after the keyword include)

Expected: Should have failed saying the file has a syntax error.
Actual: Progam terminated abnormally with the following stack trace:

PHP Catchable fatal error: Argument 1 passed to PHP_Depend_Parser::_parseAssignmentExpression() must be an instance of PHP_Depend_Code_ASTNode, null given, called in /usr/share/pear/PHP/Depend/Parser.php on line 2702 and defined in /usr/share/pear/PHP/Depend/Parser.php on line 4206
PHP Stack trace:
PHP 1. {main}() /usr/bin/phpmd:0
PHP 2. PHP_PMD_TextUI_Command::main() /usr/bin/phpmd:41
PHP 3. PHP_PMD_TextUI_Command->run() /usr/share/pear/PHP/PMD/TextUI/Command.php:151
PHP 4. PHP_PMD->processFiles() /usr/share/pear/PHP/PMD/TextUI/Command.php:129
PHP 5. PHP_PMD_Parser->parse() /usr/share/pear/PHP/PMD.php:203
PHP 6. PHP_Depend->analyze() /usr/share/pear/PHP/PMD/Parser.php:127
PHP 7. PHP_Depend->_performParseProcess() /usr/share/pear/PHP/Depend.php:306
PHP 8. PHP_Depend_Parser->parse() /usr/share/pear/PHP/Depend.php:560
PHP 9. PHP_Depend_Parser->_parseOptionalStatement() /usr/share/pear/PHP/Depend/Parser.php:369
PHP 10. PHP_Depend_Parser->_parseClassDeclaration() /usr/share/pear/PHP/Depend/Parser.php:5571
PHP 11. PHP_Depend_Parser->_parseTypeBody() /usr/share/pear/PHP/Depend/Parser.php:571
PHP 12. PHP_Depend_Parser->_parseMethodOrFieldDeclaration() /usr/share/pear/PHP/Depend/Parser.php:742
PHP 13. PHP_Depend_Parser->_parseMethodDeclaration() /usr/share/pear/PHP/Depend/Parser.php:861
PHP 14. PHP_Depend_Parser->_parseCallableDeclaration() /usr/share/pear/PHP/Depend/Parser.php:1095
PHP 15. PHP_Depend_Parser->_parseScope() /usr/share/pear/PHP/Depend/Parser.php:1142
PHP 16. PHP_Depend_Parser->_parseOptionalStatement() /usr/share/pear/PHP/Depend/Parser.php:5416
PHP 17. PHP_Depend_Parser->_parseOptionalExpression() /usr/share/pear/PHP/Depend/Parser.php:5580
PHP 18. PHP_Depend_Parser->_parseIncludeExpression() /usr/share/pear/PHP/Depend/Parser.php:2637
PHP 19. PHP_Depend_Parser->_parseRequireOrIncludeExpression() /usr/share/pear/PHP/Depend/Parser.php:1521
PHP 20. PHP_Depend_Parser->_parseOptionalExpression() /usr/share/pear/PHP/Depend/Parser.php:1588
PHP 21. PHP_Depend_Parser->_parseAssignmentExpression() /usr/share/pear/PHP/Depend/Parser.php:2702

**Comment by ravage84** [comment]
I'm closing this as I think one should lint the files first before checking them with PHPMD.
