### ISSUE TITLE
Output to unit testing xml report

### ISSUE THREAD

**Issue by johnwc** [phpmd/phpmd#762]
To really help in using in CI builds, it would be nice to have it support being able to write the findings to a XML file. Most CI frameworks know how to read [NUnit ](https://github.com/nunit/docs/wiki/Test-Result-XML-Format) or [JUnit](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) formatted xml docs and report on them.

**Comment by tvbeek** [comment]
@johnwc there is an xml output and with the option --reportfile you can decide to save the result in a file and not to output it.

Example: `phpmd src/ xml codesize --reportfile phpmdresults.xml`

**Comment by johnwc** [comment]
Does it output to one of those two XML formats? We use Azure DevOps [publish test results task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml), and it only supports a handful of XML formats.

**Comment by ravage84** [comment]
@john-whitley PHPMD currently outputs to XML in the PMD format, which makes most sense as PHPMD is a PHP derivate of the Java tool.

In https://github.com/phpmd/phpmd/pull/539 we discuss a JUnit compatible format.
