### ISSUE TITLE
New ClassNameLength Rule to Check for the Length of a Class Name

### ISSUE THREAD

**Issue by ravage84** [phpmd/phpmd#763]
Currently, there is no rule to check for the length of a class name, it seems.
We should consider adding one.

The idea originated in https://github.com/phpmd/phpmd/pull/747#issuecomment-620924505

**Comment by ravage84** [comment]
@frankdekker thank you for your work on #747.

Would you be interested to implement a new ``LongClassName`` rule which also supports the suffix property of this PR?

**Comment by ravage84** [comment]
@frankdekker's answer:

@ravage84
That would be interesting rule. Sure. You have a recommendation of the default "max" length for a class name?

**Comment by ravage84** [comment]
> That would be interesting rule. Sure. You have a recommendation of the default "max" length for a class name?

@frankdekker not really.

I didn't find any such rule in [Java's PMD](https://pmd.github.io/latest/).

In PhpStorm the default settings seem to be these:

![grafik](https://user-images.githubusercontent.com/625761/80578608-03202b00-8a09-11ea-957e-67ce2f33191e.png)

16 characters seems to b rather low, though. I would go with 20 characters.

**Comment by ravage84** [comment]
@frankdekker 's answer:

@ravage84 
Interesting example from phpstorm. Instead of making it a LongClassName rule, could do a ClassNamingConventions rule. Similar to ConstantNamingConventions. 

**With properties:**
- pattern:  (default: [A-Z][A-Za-z0-9]*)
- min:   (default: 4)
- max:   (default: 20)
- subtract-suffixes: (default: none)

Thoughts?

**Comment by ravage84** [comment]
@frankdekker 

In the past, we had very specific rules. The benefit of that is that one can cherry pick what one needs.

How about we go a middle way and do a ``ClassNameLength`` rule, which covers only the mimimum and maxiumum length including your suffix property?

- ~pattern: (default: [A-Z][A-Za-z0-9]*)~
- min: (default: 4)
- max: (default: 20)
- subtract-suffixes: (default: none)


@kylekatarnls, @tvbeek, @MarkVaughn  & @roukmoute your thoughts?

**Comment by MarkVaughn** [comment]
I like it
Nit would be that I'm not sure why the default class name minimum should be 4 when the variables are 3. 
Words like App, Bus, Log appear in projects such as Laravel.

**Comment by MarkVaughn** [comment]
Also I'd be kind of confused with the inconsistency when we have `LongVariable` & `ShortVariable` in the naming rules, but `ClassNameLength` is one. Intuitively I'd be looking for  `LongClass` & `ShortClass` then

**Comment by tvbeek** [comment]
I think that if we have it in one rule we also need to check the length just once. But it should also need to have the option to check only the min or max.

**Comment by frankdekker** [comment]
Good suggestions. My proposal:

LongClassName
- max: 20
- subtract-suffixes: (none)
- "exclude" or  "exclude-pattern" (regex pattern to exclude certain class names)
  (regex pattern to exclude certain class names. For me i would exclude anything that ends with "Test" or "TestHelper")

ShortClassName
- min: 3

**Reasons:**
- A single purpose rule for the name already exists: CamelCaseClassName
- Continue the single purpose rules as ShortVariable, LongVariable, ShortMethod
- subtract-suffixes would only affect "max".  This is now more clear as it a separate rule
- added the exclude to be able to exclude anything that ends with "Test" or "TestHelper" for example.
