### ISSUE TITLE
Website latset URL not pointing to real PHAR file.

### ISSUE THREAD

**Issue by petermcd** [phpmd/phpmd#796]
## Description
I have attempted to download the phar file from the site using the following url:

* https://phpmd.org/static/latest/phpmd.phar

This results in a 9 byte file with the conten of not found.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [ ] Tell if you have the possibility to create a Pull Request to solve this issue.
* [ ] If possible add a URL to the incorrect website page or documentation file.
* [x] This issue is about 1 documentation or website issue and nothing more.

**Comment by kylekatarnls** [comment]
I think "latest" possibly target our draft version of 2.9.0, you can use this meanwhile:
https://phpmd.org/static/2.8.2/phpmd.phar

**Comment by kylekatarnls** [comment]
Cause of the bug confirmed:
https://travis-ci.org/github/phpmd/phpmd/jobs/689744953#L279

I will add a filter to ignore drafts.

**Comment by petermcd** [comment]
thanks @kylekatarnls  managed to download 2.8.2 after searching a bit last night.

**Comment by kylekatarnls** [comment]
Fixed. Thank your for the report.
