### ISSUE TITLE
Array shorthand for list() will raise undefined variables rule error

### ISSUE THREAD

**Issue by bomas13** [phpmd/phpmd#799]
- PHPMD version: 2.8.2
- PHP Version: 7.3.14
- Installation type: composer
- Operating System / Distribution & Version: ubuntu

### Current Behavior
Content of `test.php`

```php
class foobar {
	public function foobar() {
		[$foo, $bar] = explode(",", "foo,bar");
	}
}
```

Command:
```bash
root@eaf26d92260d:/app# vendor/bin/phpmd /app/test.php text cleancode
/app/test.php:5	Avoid using undefined variables such as '$foo' which will lead to PHP notices.
/app/test.php:5	Avoid using undefined variables such as '$bar' which will lead to PHP notices.
```

---

```php
class foobar {
	public function foobar() {
		$foo = $bar = null;
		[$foo, $bar] = explode(",", "foo,bar");
	}
}
```

Command:
```bash
root@eaf26d92260d:/app# vendor/bin/phpmd /app/test.php text cleancode
root@eaf26d92260d:/app#
```

---

on the other hand:
```php
class foobar {
	public function foobar() {
		list($foo, $bar) = explode(",", "foo,bar");
	}
}
```

```bash
root@eaf26d92260d:/app# vendor/bin/phpmd /app/test.php text cleancode
root@eaf26d92260d:/app#
```

### Expected Behavior
I expected that the array shorthand for list() will not raise an error

### Steps To Reproduce:
see above.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by kylekatarnls** [comment]
Duplicates #725 and fixed in `"phpmd/phpmd": "dev-master"` (e.g. next version).

Thanks.
