### ISSUE TITLE
Out ot the box usage in combination with composer of all rules failes throws error Property $exceptions does not exist.

### ISSUE THREAD

**Issue by DannyvdSluijs** [phpmd/phpmd#80]
When having composer.json with 
```javascript
"require-dev": {
        "phpmd/phpmd": "dev-master",
```

And build.xml with
```xml
<target name="phpmd" description="Perform project mess detection using PHPMD creating a log file for the continuous integration server">
        <exec executable="./vendor/bin/phpmd">
            <arg path="${basedir}/" />
            <arg value="xml" />
            <arg value="cleancode,codesize,controversial,design,naming,unusedcode" />
            <arg value="--exclude" />
            <arg value="${basedir}/cache,${basedir}/vendor,${basedir}/build" />
            <arg value="--reportfile" />
            <arg value="${basedir}/build/logs/pmd.xml" />
        </exec>
    </target>
```

And running the command
```bash
ant phpmd
```
The following output is shown:
```bash
Buildfile: /var/www/bob/build.xml

phpmd:
     [exec] Property $exceptions does not exist.
     [exec] Result: 1

BUILD SUCCESSFUL
```

**Comment by cstrosser** [comment]
We recently started experiencing this exact problem after the update to 2.2.1.  Reverting to 2.2.0 makes the problem go away.  It seems to be limited to something within the naming.xml file, which when disabled, eliminates the "exceptions" message.  If I compared correctly, it seems there was one change to the naming.xml file in the 2.2 release.  Was there maybe an inadvertent BC break?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="PHPMD settings"
    xmlns="http://pmd.sf.net/ruleset/1.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sf.net/ruleset/1.0.0
	   http://pmd.sf.net/ruleset_xml_schema.xsd"
    xsi:noNamespaceSchemaLocation="http://pmd.sf.net/ruleset_xml_schema.xsd">
    <description>PHPMD rules for ZF2</description>

    <rule ref="rulesets/codesize.xml"/>
    <rule ref="rulesets/design.xml"/>
    <rule ref="rulesets/unusedcode.xml"/>

    <rule ref="rulesets/naming.xml">
        <exclude name="ShortVariable" />
        <exclude name="LongVariable" />
        <exclude name="BooleanGetMethodName" />
    </rule>
</ruleset>
```

**Comment by ravage84** [comment]
@cstrosser please create a separate issue next time, even if it could be related.

Those are the relevant changes between 2.2.0 and 2.2.1:
https://github.com/phpmd/phpmd/compare/2.2.0...phpmd:2.2.1#diff-0fb615195fc1c30dc57b0516a3ccfeb6R73
https://github.com/phpmd/phpmd/compare/2.2.0...phpmd:2.2.1#diff-0fb615195fc1c30dc57b0516a3ccfeb6R97
https://github.com/phpmd/phpmd/compare/2.2.0...phpmd:2.2.1#diff-ffdb8bc5d60830fdf97b6ec671fac4bcR78
https://github.com/phpmd/phpmd/compare/2.2.0...phpmd:2.2.1#diff-59d8d3eb64698d9c050a2e6a58f0298cR67
https://github.com/phpmd/phpmd/compare/2.2.0...phpmd:2.2.1#diff-8b075d4f7a3d7126e3d442f2e7e49af1R33
https://github.com/phpmd/phpmd/compare/2.2.0...phpmd:2.2.1#diff-8b075d4f7a3d7126e3d442f2e7e49af1R86

Not sure why it is complaining about  a missing $exceptions though.
As you can see it swallows a missing field silently:
https://github.com/phpmd/phpmd/compare/2.2.0...phpmd:2.2.1#diff-0fb615195fc1c30dc57b0516a3ccfeb6R99

May be it does not at some other place @manuelpichler ?

**Comment by cstrosser** [comment]
Looks like the OutOfBoundsException wasn't imported.

**Comment by ravage84** [comment]
True, could you test it with the current master?

**Comment by cstrosser** [comment]
Tested against master, and can confirm no exception is thrown.

**Comment by ravage84** [comment]
Many thanks. @manuelpichler is there something that blocks a patch release?

**Comment by manuelpichler** [comment]
@ravage84 No, a patch release seems to be valid here.
