### ISSUE TITLE
"Avoid using undefined variables" with short version of list()

### ISSUE THREAD

**Issue by tpogadl** [phpmd/phpmd#800]
PHPMD version: master
PHP Version: 7.4.6
Installation type: composer
Operating system: macOS Catalina 10.15.5

If you define variables like this, no phpmd error occurs:

```php
$array = ['foo' => 'abc', 'bar' => 'def'];
list(
    'foo' => $foo,
    'bar' => $bar
) = $array;
echo $foo;
echo $bar;
```

But if you use the short syntax of list() with [] = $array, then phpmd will give the following errors:
> Avoid using undefined variables such as '$foo' which will lead to PHP notices.
> Avoid using undefined variables such as '$bar' which will lead to PHP notices.

```php
$array = ['foo' => 'abc', 'bar' => 'def'];
[
    'foo' => $foo,
    'bar' => $bar
] = $array;
echo $foo;
echo $bar;
```

As the meaning of the two code pieces is the same, phpmd should also understand the short version syntax.
Addition: it is the same without the usage of the array index inside list() or [].

**Comment by kylekatarnls** [comment]
Duplicates #725 and fixed in "phpmd/phpmd": "dev-master" (e.g. next version).

Thanks.
