### ISSUE TITLE
Append / Show rule name before error message

### ISSUE THREAD

**Issue by Morgy93** [phpmd/phpmd#815]
## Description
Currently I'm seeing:
`Product.php:15       Avoid excessively long variable names like $productAttributeRepository. Keep variable name length under 20.`
What I would love to see:
`Product.php:15       [PHPMD.LongVariable]: Avoid excessively long variable names like $productAttributeRepository. Keep variable name length under 20.`

So it would be fast and easy to determine the exact rule(s) to suppress. =) (Or read additional info about in the documentation)

## Checks before submitting
* [X] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [X] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [X] Tell if you have the option to provide the code for this proposal.
* [X] This issue is about 1 feature proposal and nothing more.
* [X] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by kylekatarnls** [comment]
I approve this idea. PRs are welcome.
