### ISSUE TITLE
Cannot load source file for class: PHP_PMD_Rule_Design_LongClass

### ISSUE THREAD

**Issue by SilkAndSlug** [phpmd/phpmd#824]
- PHPMD version: 2.8.1 [or 'latest'; see other bug]
- PHP Version: PHP 5.6.40-29+0~20200514.35+debian10~1.gbpcc49a4 (cli)
- Installation type: composer global
- Operating System / Distribution & Version: Debian Stretch

### Current Behavior
$ phpmd src/ text tests/phpmd.xml
Cannot load source file for class: PHP_PMD_Rule_Design_LongClass

### Expected Behavior
Run given tests on src/ directory

Tests ran weekly until 2020-08-31. Testing on 2020-09-07 failed. I run `composer global update --optimize-autoloader --prefer-stable --with-dependencies --prefer-dist` every Sunday, via Cron.

### Steps To Reproduce:
Attempt to run phpmd

**Comment by SilkAndSlug** [comment]
My config file:
[phpmd.xml.txt](https://github.com/phpmd/phpmd/files/5189357/phpmd.xml.txt)

**Comment by SilkAndSlug** [comment]
The name of the class is irrelevant; deleting that rule from my phpmd.xml triggers the same error for the next rule in sequence. Deleting all rules doesn't trigger the error.

**Comment by kylekatarnls** [comment]
Hello, since [2.9.0](https://github.com/phpmd/phpmd/releases/tag/2.9.0) the snake_cased class are no longer available.
`PHP_PMD_Rule_Design_LongClass` is now available as `PHPMD\Rule\Design\LongClass` and the same for every `PHP_PMD_*` classes as this casing was in contradiction with the naming convention PHPMD recommend to follow and prevent the explicit import we also recommend.

The recommended way is to import them with `use PHPMD\Rule\Design\LongClass;` in the top of your file then use `LongClass` in the rest of the file.

Thanks,

**Comment by SilkAndSlug** [comment]
To clarify: are you saying that v2.8.1 is broken because something changed in v2.9.0? And that the fix is to `use namespace` at the top of my XML file? Or at the top of every PHP file I want to test? I've not added any custom code for PHPMD, so I didn't expect your namespacing to affect me.

**Comment by SilkAndSlug** [comment]
Ah, no. I'm `composer global show phpmd/phpmd` says I'm running v2.9.0

**Comment by SilkAndSlug** [comment]
Okay: progress -- thanks to adding debug_print_backtrace() to ~/.composer/vendor/phpmd/phpmd/src/main/php/PHPMD/Exception/RuleClassFileNotFoundException.php ...

The error is in my XML file(s) -- wot I copied from the PHPMD docs back when dinosaurs roamed the earth. 

Each of my <rule> tags has a class attribute e.g. `class="PHP_PMD_Rule_Naming_BooleanGetMethodName"`. Changing that to e.g. `class="PHPMD\Rule\Naming\BooleanGetMethodName"` fixed the problem. I did it with these commands:

sed -i 's|class=PHP_PMD_|class=PHPMD\\|g' tests/phpmd*.xml
sed -Ei 's|class="([^_]*)_|class="\1\\|g' tests/phpmd*.xml

The first changes the prefix to PHPMD ; the second changes one underscore to a backslash -- you should run it maybe three times in case of classes with lots of underscores.

**Comment by kylekatarnls** [comment]
Oh yes, I though it happened in PHP file (custom rule for instance). Indeed names should be changed too in XML files.

**Comment by kylekatarnls** [comment]
About the version it should not happen in 2.8.1, but I though you meant you stayed at 2.8.1 because unable to update due to the error.

Are you sure the phpmd you run (in the composer global vendor) is in 2.8.1 and fail to parse the underscore case rule names?

**Comment by SilkAndSlug** [comment]
[I'm actually running v2.9](https://github.com/phpmd/phpmd/issues/824#issuecomment-689995813). I think we're now discussing bug #820

**Comment by kylekatarnls** [comment]
Oh yes, sorry for that.
