### ISSUE TITLE
Fatal error while analyzing anonymous class

### ISSUE THREAD

**Issue by mprochowski** [phpmd/phpmd#829]
- PHPMD version: 2.9.1
- PHP Version: 7.4.10
- Installation type: composer
- Operating System / Distribution & Version: Alpine Linux in Docker

### Current Behavior
```
# vendor/bin/phpmd phpmd-test.php ansi cleancode,codesize,controversial,design,naming,unusedcode
PHP Fatal error:  Uncaught Error: Call to a member function getFileName() on null in /data/vendor/phpmd/phpmd/src/main/php/PHPMD/AbstractNode.php:201
Stack trace:
#0 /data/vendor/phpmd/phpmd/src/main/php/PHPMD/AbstractNode.php(117): PHPMD\AbstractNode->getFileName()
#1 /data/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php(232): PHPMD\AbstractNode->getFirstChildOfType('FormalParameter...')
#2 /data/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php(98): PHPMD\Rule\CleanCode\UndefinedVariable->collectParameters(Object(PHPMD\Node\MethodNode))
#3 /data/vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php(71): PHPMD\Rule\CleanCode\UndefinedVariable->collect(Object(PHPMD\Node\MethodNode))
#4 /data/vendor/phpmd/phpmd/src/main/php/PHPMD/RuleSet.php(255): PHPMD\Rule\CleanCode\UndefinedVariable->apply(Object(PHPMD\Node\MethodNode))
#5 /data/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(259): PHPMD\RuleSet->apply(Object(PHPMD\Node\MethodNode))
#6 /data/vendor/php in /data/vendor/phpmd/phpmd/src/main/php/PHPMD/AbstractNode.php on line 201
```

### Expected Behavior
Working properly without `Fatal error`.

### Steps To Reproduce:
Run `cleancode` rule:
```
<?php
class TestCase
{
    public function getAnonymousClass()
    {
        return new class {
            public function get(): string
            {
                return '';
            }
        };
    }
}
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by kylekatarnls** [comment]
I confirm I can reproduce it with your code. I will inspect.

**Comment by kylekatarnls** [comment]
I can reproduce it in a real project but not in unit tests where the file name is properly set and displayed in the output. I have to find first what's different in tests so it can actually detect regressions.

**Comment by ymilin** [comment]
I have it this error too for the same reason (use of anonymous classes)

Just want to add that it works with PHPMD version: 2.8.2 and was introduced by version 2.9.0.

**Comment by kylekatarnls** [comment]
Yes, actually anonymous classes were not handled at all before 2.9.0. So PHPMD was not able to check most of the rules in it.

**Comment by Okipa** [comment]
Hi there, it seems that a regression occured. I'm using phpmd 2.9.1 and using anonymous classes triggered the following error : `Uncaught Error: Call to a member function getFileName() on null in /var/www/html/vendor/phpmd/phpmd/src/main/php/PHPMD/AbstractNode.php:201`.

Has anybody encountered similar issue ?

**Comment by kylekatarnls** [comment]
2.9.1 is the version which has the bug. Sorry for the delay but 2.10.0 has not yet been released. Meanwhile you can use `dev-master`.

**Comment by Okipa** [comment]
@kylekatarnls My mad, I understood that was already fixed. Thanks for the fast answer, will wait for the 2.10.0 ! 👍
