### ISSUE TITLE
error if preg_match_all third parameter doesn't exist yet while it that isn't needed

### ISSUE THREAD

**Issue by tvbeek** [phpmd/phpmd#840]
- PHPMD version: master (2.9+)
- PHP Version: 7.4
- Installation type: git checkout
- Operating System / Distribution & Version: docker (laradock)

Example code

```php
preg_match_all($this->regexp, $node->getDocComment(), $matches);
foreach (array_keys($matches[0]) as $i) {
    $name = $matches[1][$i];
    $value = trim($matches[2][$i], '" ');

    $this->annotations[] = new Annotation($name, $value);
}
```

### Current Behavior
src/main/php/PHPMD/Node/Annotations.php:48       Avoid using undefined variables such as '$matches' which will lead to PHP notices.

### Expected Behavior
No errors because preg_match_all set the variable by reference

This was found while cleaning our own code in #839

**Comment by kylekatarnls** [comment]
I re-found the fix: #828 it's still waiting for review.

I close this issue because it duplicates #672
