### ISSUE TITLE
Message: implode(): Passing glue string after array is deprecated. Swap the parameters in Codeigniter using google client api for google drive

### ISSUE THREAD

**Issue by FahadTariq476-dev** [phpmd/phpmd#842]
**A PHP Error was encountered**
Severity: 8192

Message: implode(): Passing glue string after array is deprecated. Swap the parameters

Filename: Service/Resource.php

Line Number: 289

Backtrace:

File: C:\xampp\htdocs\googledrivecod\vendor\google\apiclient\src\Google\Service\Resource.php
Line: 289
Function: implode

File: C:\xampp\htdocs\googledrivecod\vendor\google\apiclient\src\Google\Service\Resource.php
Line: 190
Function: createRequestUri

File: C:\xampp\htdocs\googledrivecod\vendor\google\apiclient-services\src\Google\Service\Drive\Resource\Files.php
Line: 245
Function: call

**Comment by tvbeek** [comment]
Hello @FahadTariq476-dev 

I currently don't understand your message. I understand that the parameter for the implode needs to be swapped. But the code you point out aren't part of PHPMD.

Can you explain what you did so we can help you?

**Comment by FahadTariq476-dev** [comment]
thanks for your reply
i am getting the implode due to old version of google client api
now its resolved

**Comment by FahadTariq476-dev** [comment]
by replacing the parameters in Resource.php 
if (count($queryVars)) {
      $requestUrl .= '?' . implode('&',$queryVars);
    }
