### ISSUE TITLE
How to dump AST structure of a php file?

### ISSUE THREAD

**Issue by retanoj** [phpmd/phpmd#845]
Such as title.

And I leave message on gitter channel, but no one online :(

**Comment by kylekatarnls** [comment]
Hi @retanoj sorry for that, I saw your message on gitter but did not have a pleasant answer. AFAIK there is no such think out of the box. We could still probably cook up a function or use some generic data dump.

**Comment by retanoj** [comment]
> Hi @retanoj sorry for that, I saw your message on gitter but did not have a pleasant answer. AFAIK there is no such think out of the box. We could still probably cook up a function or use some generic data dump.

em...  Thank you for your replying.
Actually after made a deep look at pmd source code, I did not find a function like that, too.
But I really think it is a good idea to cook up a dump AST function for rule maker.
