### ISSUE TITLE
Unexpected token appears in PHP 8.0

### ISSUE THREAD

**Issue by hrs-o** [phpmd/phpmd#853]
- PHPMD version: 2.9.1
- PHP Version: 8.0
- Installation type: composer
- Operating System / Distribution & Version: Docker Image `php:8.0-fpm-alpine`

### Current Behavior

It worked fine in PHP7.4, but in PHP8.0 it shows `Unexpected token:` in all the .php files it inspects.

### Expected Behavior

The process is completed normally.

### Steps To Reproduce:

- `$ phpmd . text phpmd.xml`

#### phpmd.xml

```xml
<?xml version="1.0"?>
<ruleset name="Custom_PHPMD">
    <description>Custom ruleset PHPMD</description>
    <rule ref="rulesets/codesize.xml" />
    <rule ref="rulesets/controversial.xml">
        <exclude name="CamelCasePropertyName" />
        <exclude name="CamelCaseParameterName" />
        <exclude name="CamelCaseVariableName" />
    </rule>
    <rule ref="rulesets/design.xml" />
    <rule ref="rulesets/unusedcode.xml" />
    <rule ref="rulesets/naming.xml">
        <exclude name="ShortVariable"/>
        <exclude name="LongVariable" />
    </rule>
    <rule ref="rulesets/naming.xml/ShortVariable">
        <properties>
            <property name="exceptions" value="id,e,tz"/>
        </properties>
    </rule>
    <rule ref="rulesets/cleancode.xml">
        <exclude name="BooleanArgumentFlag"/>
        <exclude name="ElseExpression"/>
        <exclude name="StaticAccess"/>
    </rule>
    <exclude-pattern>*/_ide_helper.php</exclude-pattern>
    <exclude-pattern>*/_ide_helper_models.php</exclude-pattern>
    <exclude-pattern>*/_ide_helper_redis.php</exclude-pattern>
    <exclude-pattern>*/database/*</exclude-pattern>
    <exclude-pattern>*/cache/*</exclude-pattern>
    <exclude-pattern>*/*.blade.php</exclude-pattern>
    <exclude-pattern>*/autoload.php</exclude-pattern>
    <exclude-pattern>*/storage/*</exclude-pattern>
    <exclude-pattern>*/docs/*</exclude-pattern>
    <exclude-pattern>*/vendor/*</exclude-pattern>
    <exclude-pattern>*/migrations/*</exclude-pattern>
    <exclude-pattern>*/tmp/*</exclude-pattern>
</ruleset>

```

#### output message

This is just one example, but other files are displayed as well.

```
/src/app/Console/Kernel.php     -       Unexpected token: App\Console, line: 3, col: 11, file: /src/app/Console/Kernel.php.
/src/app/Exceptions/Handler.php -       Unexpected token: App\Exceptions, line: 3, col: 11, file: /src/app/Exceptions/Handler.php.
...
```

As you can see in the file below, an `Unexpected token` is displayed at the time of the namespace.

https://github.com/laravel/laravel/blob/8.x/app/Console/Kernel.php
https://github.com/laravel/laravel/blob/8.x/app/Exceptions/Handler.php

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
  * Searching for issues in PHP8 and  8.0 and Unexpected 
* [x] I have added every step to reproduce the bug.
* [ ] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by kylekatarnls** [comment]
Hello,

PHP 8 introduces breaking changes in tokens of the languages. We're working on it from the PDepend side:
https://github.com/pdepend/pdepend/issues/491
https://github.com/pdepend/pdepend/pull/498

Thanks for your patience.

**Comment by hrs-o** [comment]
Thank you.
understood.

**Comment by kylekatarnls** [comment]
But you were right to open an issue here, so phpmd users can know the status without digging into PDepend issues. So I'll keep this open for follow-up :)

**Comment by cnizzardini** [comment]
Is this resolved yet?

**Comment by kylekatarnls** [comment]
As per issue status, it's planned for PHPMD 2.10.0

**Comment by jpresutti** [comment]
This is actually a major issue blocking usage entirely. This should not be considered a feature, and should be a bug on the current version.

**Comment by kylekatarnls** [comment]
I can't say it's not critical. But "bug" would just be an incorrect label on this. It's a compatibility issue. Be known everything is in the pipe:
https://github.com/pdepend/pdepend/pulls?q=is%3Apr+is%3Aopen+label%3Aphp8.0

Once all that merged, we'll be able to release a compatible version.

**Comment by adamcameron** [comment]
Just a note on this for ppl like me for whom this might not initially be obvious ;-). If one forces `"pdepend/pdepend": "^2.9"` in composer.json, it seems to sort the issue out, even when still on phpmd v2.9.x.

**Comment by kylekatarnls** [comment]
Yes actually PHPMD and PDepend versions are not sync, the 2.9 match is just a coincidence. PHPMD 2.9.1 requires pdepend >= 2.8.0. It's a minimal requirement so you can have more (pdepend/pdepend#dev-master will be 2.9) but PDepend 2.9 is not yet released as stable so it does not automatically step into it.

**Comment by bperel** [comment]
Pdepend 2.9.0 is [out](https://github.com/pdepend/pdepend/releases/tag/2.9.0) since a few days but it could be preferable to wait for the [release of 2.9.1](https://github.com/pdepend/pdepend/milestone/24) since 2.9.0 doesn't support all the new PHP 8 syntax

**Comment by kylekatarnls** [comment]
Actually there is no reason to wait to update. If you have PHP 8 syntax or run PHP 8, PDepend 2.8.0 is not working, while 2.9.0 will work unless you use 1 of the 2 remaining syntaxes to be implemented:
https://github.com/pdepend/pdepend/milestone/24

If you are on PHP 7, both goes well. So I can see any relevant reason to prefer to stick to 2.8.0 over 2.9.0 until we fulfill the support.

If you're on composer, you can safely update, And for the phar build, the next one will embed PDepend 2.9.0 (unless 2.9.1 is out before).

**Comment by AdrienBr** [comment]
Same here, phpmd 2.10.1 & pdepend 2.9.1 raise errors on structures like "match", or PHPStorm attributes like #[ExpectedValues()]

**Comment by tvbeek** [comment]
@AdrienBr yes please, we mostly try to work on the open issues. An issue with an example of the code and the error you get should be very nice to have. (if there isn't already an issue open)
