### ISSUE TITLE
Exception at AbstractPHPParser.php on line 6600 , required ASTValue and passed NULL

### ISSUE THREAD

**Issue by pagarwal-ignitetech** [phpmd/phpmd#859]
Phpmd release : 2.9.1

Getting below exception while running Phpmd on a codebase:

Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\ASTVariableDeclarator::setValue() must be an instance of PDepend\Source\AST\ASTValue, null given, called in phar:///usr/bin/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 6600 and defined in phar:///usr/bin/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTVariableDeclarator.php:82 PHP Fatal error: Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\ASTVariableDeclarator::setValue() must be an instance of PDepend\Source\AST\ASTValue, null given, called in phar:///usr/bin/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 6600 and defined in phar:///usr/bin/phpmd/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTVariableDeclarator.php:82

**Comment by kylekatarnls** [comment]
Hello, you can use this temporary fix: `composer require pdepend/pdepend:dev-allow-null --dev` it should allow the null value there and also output a `debug.log` file which should indicate where it found this value.

Please provide the code around this info and the file (or try to reduce to the minimum chunk that reproduces the bug). It would help us to fix it properly and permanently.

**Comment by pagarwal-ignitetech** [comment]
I am using cli command, where to provide this `composer require ...`

**Comment by kylekatarnls** [comment]
I built it as a phar:
https://github.com/kylekatarnls/phpmd/suites/1784470108/artifacts/34123676

You can use it to produce the debug.log that will helps to know what phpmd fails on.

**Comment by pagarwal-ignitetech** [comment]
> I built it as a phar:
> https://github.com/kylekatarnls/phpmd/suites/1784470108/artifacts/34123676
> 
> You can use it to produce the debug.log that will helps to know what phpmd fails on.

I used the above phar, but how to get debug log through command line option. Can you please help in this regards?

**Comment by pagarwal-ignitetech** [comment]
> I built it as a phar:
> https://github.com/kylekatarnls/phpmd/suites/1784470108/artifacts/34123676
> 
> You can use it to produce the debug.log that will helps to know what phpmd fails on.

The command got success with the above artifact

**Comment by kylekatarnls** [comment]
Yes but please provide the `debug.log` file that has been generated in your working directory, it should tell which file made PHPMD fail. Thanks. 🙏

**Comment by pagarwal-ignitetech** [comment]
> Yes but please provide the `debug.log` file that has been generated in your working directory, it should tell which file made PHPMD fail. Thanks. 🙏

Only got this line `Unexpected token: =, line: 40, col: 29, file: /home/codebase/vendor/symfony/http-client/CurlHttpClient.php` in logs where CurlHttpClient.php is attached

[codebase.zip](https://github.com/phpmd/phpmd/files/5841994/codebase.zip)

**Comment by pagarwal-ignitetech** [comment]
also after deleting this file from codebase it worked well in release too

**Comment by kylekatarnls** [comment]
Thanks, be aware then scanning only your source (excluding vendor) will save a lot of execution time.

**Comment by tvbeek** [comment]
@pagarwal-ignitetech If I'm correctly your issue is resolved. That is why I close it.
Feel free to say if I'm incorrect so I or someone else can reopen this issue.
