### ISSUE TITLE
phpmd.org website is down ?

### ISSUE THREAD

**Issue by jeckel** [phpmd/phpmd#863]
## Description
It looks like the phpmd website does no longer exists [website](https://phpmd.org/), don't know if it's a github issue, or a repository issue (can't find the documentation repository)

I have 404 page:
![Screenshot_20210108_084124](https://user-images.githubusercontent.com/2981531/103987778-4ed8c600-518d-11eb-85fe-fabe40fe093c.png)

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] Tell if you have the possibility to create a Pull Request to solve this issue.
* [x] If possible add a URL to the incorrect website page or documentation file.
* [x] This issue is about 1 documentation or website issue and nothing more.

**Comment by federicoiosue** [comment]
I suppose is due to Github Actins pipeline ([even if it worked](https://github.com/phpmd/phpmd/actions/runs/469620184))

**Comment by kylekatarnls** [comment]
Very likely, it's due to the CNAME deletion that happened in the GitHub Action:
https://github.com/phpmd/phpmd/runs/1664216748#step:9:127

**Comment by jeckel** [comment]
Website is back
