### ISSUE TITLE
Exclude global namespace classes from MissingImport rule

### ISSUE THREAD

**Issue by danepowell** [phpmd/phpmd#868]
## Description
The [MissingImport rule](https://github.com/phpmd/phpmd/blob/1964e0f81ceec3c2b15281d2709dbb66b68873c1/src/main/resources/rulesets/cleancode.xml#L185) flags any class that is referenced via its FQN. This makes sense for any class that is part of a namespace, but it's not so clear that this should apply to classes in the global namespace (e.g. `Exception`, `RuntimeException`).

This isn't just an aesthetic annoyance, it makes it impossible to use this PHPMD rule on some types of projects (e.g. Drupal) that specifically enforce that classes in the global namespace be fully qualified:
- https://www.drupal.org/docs/develop/coding-standards/namespaces#s-use-ing-classes
- https://www.drupal.org/project/coder/issues/3120001#comment-13993942

For instance, this passes Drupal coding standards:
```php
<?php

namespace Foo;

throw new \Exception;
```

This passes PHPMD:
```php
<?php

namespace Foo;

use \Exception;

throw new Exception;
```

But there's no way that I can tell to make it work with both standards.

Can we exclude global namespace classes from this rule (either by default or as an option)?

I _might_ be able to submit a PR if you approve, I'm not sure if rules can have options.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by kylekatarnls** [comment]
Hello,

Thanks for the proposal.

> but it's not so clear that this should apply to classes in the global namespace

It's completely clear and on purpose. Global namespace is mentioned as an example in the doc using `stdClass` and the initial request #321 uses `RuntimeException`.

I don't see any reason to enforce import for `\Foo\Exception` class and not for `\Exception`, and would personally disapprove this Drupal coding standard, this is a class you use in your code and it should appear in your coupling as any other.

But yet I'm not against an option for that as long as the current behavior remains the default.
