### ISSUE TITLE
Add a baseline for existing projects

### ISSUE THREAD

**Issue by evs-xsarus** [phpmd/phpmd#871]
## Description
Taken from PHPStan, https://phpstan.org/user-guide/baseline :

> declare the currently reported list of errors as “the baseline” and cause it not being reported in subsequent runs. It allows you to be interested in violations only in new and changed code.

Supposedly, there is someone working on this, as I found this:

https://gitter.im/phpmd/community?at=5f4426e748237809373e3af4
> Anders Jenbo @AJenbo aug. 24 2020 22:45
> Going to work on the baseline feature.

**Comment by AJenbo** [comment]
Haven't had time to work on this yet unfortunately.

**Comment by frankdekker** [comment]
I'm looking for this functionality as well. I'll work on a PR.
