### ISSUE TITLE
Provide uncompressed PHAR to improve portability

### ISSUE THREAD

**Issue by henryju** [phpmd/phpmd#88]
Hi,

bzip2 support requires some extra configuration (at least on Windows) so it reduces the interest to use the PHAR archive as a quickstart solution.
Could you please provide an uncompressed version of phpmd.phar?

Thanks

Julien

**Comment by henryju** [comment]
I'm no more working on this topic, so feel free to close this issue if you consider it as outdated.

**Comment by kylekatarnls** [comment]
I think we should not multiply the exports variants. Now our build process in the source code so anyone is free to create his own process from it and create his own phar with different options. I would rather close this issue.

**Comment by bellingard** [comment]
This issue is definitely outdated, please feel free to close.
