### ISSUE TITLE
Phar throwing errors in PHP 8.0.

### ISSUE THREAD

**Issue by mikebronner** [phpmd/phpmd#881]
- PHPMD version: 2.10.0
- PHP Version: 8.0.3
- Installation type: phar
- Operating System / Distribution & Version: macOS

### Current Behavior
I'm seeing multiple errors during a single lint execution.
```
./Bin/phpmd Test.php json cleancode,codesize,controversial,design,naming,unusedcode 
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 54

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 54
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 68

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/config/Util/XmlUtils.php on line 68
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 517

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 517
PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 519

Deprecated: Function libxml_disable_entity_loader() is deprecated in phar:///<xxxxx>/Bin/phpmd/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 519
{
    "version": "2.10.0snapshot202104261849",
    "package": "phpmd",
    "timestamp": "2021-04-27T02:27:17+00:00",
    "files": [
        {
            "file": "\/Users\/mike\/Developer\/phpmd.novaextension\/Test.php",
            "violations": [
                {
                    "beginLine": 3,
                    "endLine": 6,
                    "package": "+global",
                    "function": null,
                    "class": "Testasfsdfsdafsdfsadfsdfsdfsdafsadfsafsdfsdfdsfdsfsdaf",
                    "method": null,
                    "description": "Avoid excessively long class names like Testasfsdfsdafsdfsadfsdfsdfsdafsadfsafsdfsdfdsfdsfsdaf. Keep class name length under 40.",
                    "rule": "LongClassName",
                    "ruleSet": "Naming Rules",
                    "externalInfoUrl": "https:\/\/phpmd.org\/rules\/naming.html#longclassname",
                    "priority": 3
                }
            ]
        }
    ]
}
```

### Expected Behavior
- The errors make it difficult to parse the results programatically.
- I would expect `libxml_disable_entity_loader()` not to be referenced when running in PHP 8.

### Steps To Reproduce:
Run the above command on the following file:
```php
<?php

class Testasfsdfsdafsdfsadfsdfsdfsdafsadfsafsdfsdfdsfdsfsdaf
{
    //
}
```

## Checks before submitting
* [X] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [X] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [X] I have added every step to reproduce the bug.
* [X] If possible I added relevant code examples.
* [X] This issue is about 1 bug and nothing more.
* [X] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by kylekatarnls** [comment]
Hello, the PHAR is a unique bundle, it's the exact same code for any PHP version, so we have to build using the lowest supported PHP version to ensure it works everywhere which prevents having latest Symfony packages in the PHAR version.

To get the latest dependencies, you need to use the composer installation. We'll get rid of old PHP version on the version 3.0. Optionally you can fork https://github.com/phpmd/phpmd/blob/master/.github/workflows/generate_phar.yml#L22 to build a PHAR for an upper version.

We could consider catching those deprecations but fixing them is not on our side.

Thanks.

**Comment by garak** [comment]
> Hello, the PHAR is a unique bundle, it's the exact same code for any PHP version, so we have to build using the lowest supported PHP version to ensure it works everywhere which prevents having latest Symfony packages in the PHAR version.

Well, you're contradicting yourself: the current PHAR indeed does not work everywhere (it's not working with PHP 8, as stated above).

**Comment by kylekatarnls** [comment]
Incorrect, libxml_disable_entity_loader() works in PHP 8, it's only deprecated.

And I'm answering the statement:

> I would expect libxml_disable_entity_loader() not to be referenced when running in PHP 8.

**Comment by garak** [comment]
It's *only* deprecated means that running phpmd will exit with a code different from 0. That's enough to say that it does not work.

**Comment by garak** [comment]
> Expecting a PHAR build to contain a different code in PHP 5, 7 or 8 is not possible, it involves to provide multiple PHAR and require user to switch from one to an other on each environment when the version may be different, we won't do that.

I guess that it's simple enough as adding a conditional based on PHP version in the code.

**Comment by kylekatarnls** [comment]
Are you suggesting we should already be compatible with PHP 12 too? 😆

**Comment by kylekatarnls** [comment]
> I guess that it's simple enough as adding a conditional based on PHP version in the code.

That's exactly how we work around incompatibility across versions.

**Comment by kylekatarnls** [comment]
Also keep in mind that `libxml_disable_entity_loader()` is called from symfony/dependency-injection, it's not in our own library code.

**Comment by garak** [comment]
> Also keep in mind that `libxml_disable_entity_loader()` is called from symfony/dependency-injection, it's not in our own library code.

You're right about this.

Anyway, I don't get why you don't want to provide PHARs for different versions, almost every library does that.
Can't you provide a single PHAR (like now) *and* versioned PHARs (for such edge cases)?

**Comment by kylekatarnls** [comment]
> running phpmd will exit with a code different from 0
No, it will exit with `0` (deprecation as you can see above are not fatal errors, process continues)

Also it's a user choice to report or not:
```
php -d error_reporting=24575 phpmd.phar folder json ...
```

> almost every library does that.
What libraries are you referring to? I think you may be mixing providing different libraries versions having different PHP support ranges (we have the 3.x branch which will drop PHP 5) with 1 version of a library that split into multiple PHARs: and for the last, I it's certainly not standard.

Users can now work around this issue easily:
- with `php -d error_reporting=24575`
- using composer instead of the phar
- build a phar from source: see our workflow: https://github.com/phpmd/phpmd/blob/master/.github/workflows/generate_phar.yml how we make the phar is also part of the open-source code

So my position (and I don't talk for the whole team) is that it's fine to fix this in 3.0.0 when we'll drop old PHP versions and so will upgrade `symfony/dependency-injection`

**Comment by garak** [comment]
This is from CircleCI:
![Schermata da 2021-06-15 12-54-19](https://user-images.githubusercontent.com/179866/122041159-f1e6d900-cdd8-11eb-8e39-fa42c6e5aa95.png)

**Comment by kylekatarnls** [comment]
Is **logs/pmd.xml** properly generated?

**Comment by garak** [comment]
> Is **logs/pmd.xml** properly generated?

XML it's generated in a previous step, that's returning exit code 0.
By the way, using `php -d error_reporting=24575` does not provide any improvement: phpmd is exiting with code 3 nonetheless

**Comment by kylekatarnls** [comment]
> XML it's generated in a previous step

The report file should be written down by phpmd with the summary of the violation, I don't get how it can be done in a previous step.

> using php -d error_reporting=24575 does not provide any improvement: phpmd is exiting with code 3 nonetheless

That's actually mean you're facing a different issue. I suspect the `3` exit code is not related to this current issue regarding `libxml_disable_entity_loader` deprecation.

**Comment by garak** [comment]
Ah, sorry I misinterpreted your previous question (and replied about configuration XML, not log one).
So, I checked the log and I'm getting an error about "Unexpected token: private" that is related to a promoted property.
So, it looks like phpmd is not supporting PHP 8 syntax 😕

**Comment by kylekatarnls** [comment]
That's what I though, I checked and the issue here returns `0` code when checking with `echo $?`

You're likely have one of the unsupported syntax listed above:
https://github.com/pdepend/pdepend/issues?q=is%3Aissue+is%3Aopen+label%3Aphp8.0

There remain very few of them regarding the whole list of new syntax support we already implemented:
https://github.com/pdepend/pdepend/issues?q=is%3Aissue+label%3Aphp8.0+is%3Aclosed

We'll gladly merge your pull-request if you're willing to fix it.

If it's not one of the known issues, please create a new one.

After that I will cleanup this issue to remain it focused on the deprecation notice issue. Fatal errors should not be handled there else we'll never keep the track of the proper priority of it.

**Comment by garak** [comment]
Thank you @kylekatarnls 
I commented on [related issue](https://github.com/pdepend/pdepend/issues/494#issuecomment-861430800)
