### ISSUE TITLE
Better Ansi Output

### ISSUE THREAD

**Issue by Kazuto** [phpmd/phpmd#898]
## Description
We've just started using phpmd in an already established codebase and the ANSI output was just confusing to read or to understand what belongs to what.

It's unclear for users who took the first look at the output that it's divided like
```
File:
-----
Findings
```

But instead of being read as
```
-----
Findings
File:
-----
```

Adding a blank like certainly would make the output more readable and easier on the eyes, like this:
| Before | After |
|--------|-------|
|![Screenshot 2021-06-10 at 11 36 14 AM](https://user-images.githubusercontent.com/25435034/121502477-7fdd5100-c9e0-11eb-98dc-8653dc7e63fb.png) |![Screenshot 2021-06-10 at 11 43 26 AM](https://user-images.githubusercontent.com/25435034/121503161-190c6780-c9e1-11eb-822f-ed1376a4a392.png)|

I have not looked into the codebase to say if I could provide a PR.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by kylekatarnls** [comment]
Sounds fair to me.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue. Please point me the file. Thanks

**Comment by tvbeek** [comment]
De different renders are place in `src/main/php/PHPMD/Renderer` so the Ansi renderer is: https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/Renderer/AnsiRenderer.php

To test for that renders is placed in: https://github.com/phpmd/phpmd/blob/master/src/test/php/PHPMD/Renderer/AnsiRendererTest.php

Because you say that you want to work on this issue I assign it to you so that it is clear for everyone. (And thanks that you want to help 👍 )

Please say it if you want to have more information 😃

**Comment by himanshu007-creator** [comment]
Can you tell where exactly to insert the new line? I am new to PHP

**Comment by kylekatarnls** [comment]
This line writes the file header to the output:
https://github.com/phpmd/phpmd/blob/master/src/main/php/PHPMD/Renderer/AnsiRenderer.php#L41

**Comment by kylekatarnls** [comment]
Hello @Kazuto, thanks to @himanshu007-creator there is now one more new line in between, you can test it requiring `"phpmd/phpmd": "dev-master"`
