### ISSUE TITLE
Pull requests already merged not yet included into the last current release 2.10.2 (22 Jul)

### ISSUE THREAD

**Issue by ricfio** [phpmd/phpmd#921]
I'm not very well versed in github projects and releases management, so sorry if my question will be trivial for you.
Is it correct that the current release of phpmd (version 2.10.2) published on July 22nd doesn't include pull requests that are already merged into the main branch, such this https://github.com/phpmd/phpmd/pull/905 (for example)?

For further details about my dubts, see my comments on the following (closed before my comments) issue, please: https://github.com/phpmd/phpmd/issues/884.

**Comment by AJenbo** [comment]
2.10.2 came out 22 Jul 2021, #905 was merged on 29 Jul. 2.10.2 does not contain #905. GitHub can do many things, but time travel is not one of them :)

**Comment by ricfio** [comment]
> 2.10.2 came out 22 Jul 2021, #905 was merged on 29 Jul. 2.10.2 does not contain #905. GitHub can do many things, but time travel is not one of them :)

Sure, but I don't understand why not publish a new release every time a PR is merged into the main branch.
With your approach it's not that easy to known which PRs are included in a release version without digging in the commit history.

I think that increase the patch version with each PR merging has no so much effort (for example from 2.10.2 to 2.10.3).

Anyway, thanks for the reply.

**Comment by AJenbo** [comment]
I don't think there is anything unique about how this project is handled.

When a release is done a certain amount of quality checks are performed to make sure things won't break. Also the version reflects the level changes contained in the release, which allows users to perform minor updates with out breakage. If the patch version was simply increased each time a change was made to the project you would have things breaking left and right for people when a feature change was merged.

If you want the beading edge code you can set the version in composer to `dev-master`, that way it will update on every change.

You can also set it to a specific hash if what you are after is having a version where your specific issue is fixed. But then you should revert once the next version comes out.

Besides the commit log there is also the release notes and change log which clearly lists what is (with PR numbers as well) included in a given release: https://github.com/phpmd/phpmd/blob/master/CHANGELOG

**Comment by kylekatarnls** [comment]
I agree, it's also possible to set the version to `^2@dev` so you keep updated with the last merged PRs until the next major (3.0) is released.
