### ISSUE TITLE
Missing `phpmd.phar`in latest release (2.11.0)

### ISSUE THREAD

**Issue by pierre42100** [phpmd/phpmd#923]
## Description
Hello, a new version of PHPMD was released yesterday : [version 2.11.0](https://github.com/phpmd/phpmd/releases/tag/2.11.0)
Unlike previous versions, this version does not include a `phpmd.phar` artefact.
I have built an automated system that relies on the presence of this file to perform auto-updates.
Did you omit on purpose to publish this file or this is an accident ?
Thank you

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] Tell if you have the possibility to create a Pull Request to solve this issue. (not relevant)
* [x] If possible add a URL to the incorrect website page or documentation file.
* [x] This issue is about 1 documentation or website issue and nothing more.

**Comment by tvbeek** [comment]
@pierre42100 Thanks for pointing out, I have added the missing file.
