### ISSUE TITLE
exclude ignore directories in xml config

### ISSUE THREAD

**Issue by sinkcup** [phpmd/phpmd#931]
## Description
now we can use `phpmd --exclude vendor` to ignore directory, but can't config it in the `phpmd.xml`.
suggestion: exclude ignore directories in xml config, such as `phpcs.xml`.

```xml
<?xml version="1.0"?>
<ruleset name="PSR12-Foo">
  <exclude-pattern>/vendor/</exclude-pattern>
  <arg name="extensions" value="php" />

  <!-- Include the whole PSR12 standard -->
  <rule ref="PSR12" />
</ruleset>
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by kylekatarnls** [comment]
exclude-pattern exists but it needs to be a glob string:
`<exclude-pattern>*/vendor/*</exclude-pattern>`
https://github.com/phpmd/phpmd/blob/9e531d61b088339078f7e5cce5390e2beeb8e810/src/test/resources/files/rulesets/exclude-pattern.xml

**Comment by tvbeek** [comment]
@sinkcup If I'm correct your issue is solved. That is why I close this issue. If that isn't the case please explain and I (or someone else) can reopen this issue.
