### ISSUE TITLE
Wordpress Error | Call to undefined function

### ISSUE THREAD

**Issue by EmadJavanmardi** [phpmd/phpmd#933]
Hi Guys
I have just noticed that one of my websites doesnt run.
when i deactivated one of my plugins the error solved but now showing this error and the site is just a blank page.

Fatal error: Uncaught Error: Call to undefined function woodmart_get_content_class() in /home/radiomeh/public_html/wp-content/themes/woodmart/page.php:17 Stack trace: #0 /home/radiomeh/public_html/wp-includes/template-loader.php(106): include() #1 /home/radiomeh/public_html/wp-blog-header.php(19): require_once('/home/radiomeh/...') #2 /home/radiomeh/public_html/index.php(17): require('/home/radiomeh/...') #3 {main} thrown in /home/radiomeh/public_html/wp-content/themes/woodmart/page.php on line 17

can anyone help?

**Comment by tvbeek** [comment]
Hello Emad,

I think you created an issue in the wrong project. This is PHPMD and has nothing to do with WordPress.
If I'm looking at your error I suspect you need to check your theme.

Good luck.
