### ISSUE TITLE
Request: New release with xdebug-handler version changes

### ISSUE THREAD

**Issue by blissdev** [phpmd/phpmd#935]
- PHPMD version: 2.11.1
- PHP Version: 8.0.13
- Installation type: composer
- Operating System / Distribution & Version: Fedora 35

A fix for this issue has already been merged in https://github.com/phpmd/phpmd/commit/f0b15167a78a9d4de7ba3bce0fbd2d927e9c40e9 (via #930). It just needs to be released so it can be utilized.

### Current Behavior
We use php-cs-fixer in tandem with phpmd and right now there is an incompatibility with their usage of `composer/xdebug-handler`.  Because of this composer downgrades phpmd to version `2.7.0` which causes breakage (it's also almost ~3 years old).

### Expected Behavior
The newest version of both libraries can be installed together.

### Steps To Reproduce:
composer.json
```json
{
    "require-dev": {
        "friendsofphp/php-cs-fixer": "*",
        "phpmd/phpmd": "*",
    }
}
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by AJenbo** [comment]
A new release will come as soon as it's ready. If you need this solved urgently I suggest either setting your phpmd version to dev-master to use the latest unreleased code, or make use of https://github.com/logical-and/composer-isolation to allow the two dependencies to coexist.
