### ISSUE TITLE
Allow certain static methods

### ISSUE THREAD

**Issue by TomHart** [phpmd/phpmd#943]
## Description
It'd be great to be able to configure in the config file certain classes/static methods that are allowed, to avoid littering the ignore comments throughout the code, and without totally disabling the check

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by tvbeek** [comment]
@TomHart thanks for your issue. I think this is a good idea to add to the project. Are you able to provide a PR with (a start of) the work that need to be done?
