### ISSUE TITLE
Add new console argument like --include

### ISSUE THREAD

**Issue by laziest-coder** [phpmd/phpmd#956]
Yeeeey I'm opening my first issue on open source project! 

Anyway, there is an argument called **--exclude** that takes list of directories to exclude, but in my case, I have only few directories to run linter out of many.

I think if there were an argument **--include/--only** that works exact same as **--exclude** but in reverse purpose, it would be easier to test only desired directories rather than excluding ton of other directories.

I would like to implement this and contribute to the project if no one has planned yet.

Thank you!

**Comment by kylekatarnls** [comment]
Hello, what's the difference with:

```
phpmd src/folder1,src/folder2 text ./phpmd.xml
```
