### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by KOLANICH** [phpmd/phpmd#96]
BUILD FAILED
E:\public_html\modules\phpmd\setup\src\main\xml\exts\requirejs.xml:150: Unable t
o delete file E:\public_html\modules\phpmd\setup\src\main\resources\extensions\d
b-mysql\mysql-connector-java-5.1.17-bin.jar

**Comment by kylekatarnls** [comment]
Indeed we no longer have `src\main\xml`, this is obsolete. Thanks for the check.
