### ISSUE TITLE
Another version of logo for small display size?

### ISSUE THREAD

**Issue by shaopeng-gh** [phpmd/phpmd#961]
## Description
Hello, we are working on adding popular linters to GitHub starter workflow,
the only question for the PHPMD pr currently is when the logo display size is small the text in the logo will not be readable.
Depending on the teams point of view this may or may not be a actual concern since user search the tool by typing in the tool name.
please review the logo currently in the pr (the one from the website), and let me know if to proceed with the current one or if the team can provide another version:
https://github.com/actions/starter-workflows/pull/1591
The required format is SVG. thanks.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] Tell if you have the option to provide the code for this proposal.
* [x] This issue is about 1 feature proposal and nothing more.
* [x] The issue has a descriptive title. For example: "Add JSON render option".

**Comment by AJenbo** [comment]
The low res square logo is just the trashcan 👍
![Screenshot_20220604-082356_Chrome](https://user-images.githubusercontent.com/204594/171987422-e30f665f-9cd1-4160-b5aa-48752858a568.jpg)

**Comment by kylekatarnls** [comment]
You can find the logo with transparency on https://github.com/phpmd

Here is the URL
https://avatars.githubusercontent.com/u/590448?s=200&v=4
![PHPMD](https://avatars.githubusercontent.com/u/590448?s=200&v=4)

Feel free to resize it in any lower size.
