### ISSUE TITLE
PHP 8.1.9 deprecation: "Symfony\Component\Config\Resource\FileResource implements the Serializable interface, which is deprecated"

### ISSUE THREAD

**Issue by romulodl** [phpmd/phpmd#971]
- PHPMD version: 2.12.0
- PHP Version: 8.1.9
- Installation type: via brew install and downloading the phar file from the website
- Operating System / Distribution & Version: macOS Monterrey (12.2.1)

### Current Behavior
Getting deprecation warnings related with `symfony/config` package.

```
PHP Deprecated:  Symfony\Component\Config\Resource\FileResource implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in phar:///usr/local/bin/phpmd/vendor/symfony/config/Resource/FileResource.php on line 21
```

### Expected Behavior
Not having these warnings.

### Steps To Reproduce:
 - Download and install the phar phpmd version 2.12.0 from the website.
 - Run phpmd with php 8.1.9 and the warnings will appear.

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] I have added every step to reproduce the bug.
* [ ] If possible I added relevant code examples.
* [x] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by AJenbo** [comment]
The phar file is made to be compatible with PHP 5.3 which require this version. If you need to run it on a later version of PHP and do not want warnings then please install via composer.
