### ISSUE TITLE
PHPMD execution failed with returned code '137'

### ISSUE THREAD

**Issue by graux** [phpmd/phpmd#99]
Hi,
I would like to report an issue and get some support if possible.
We have a pretty big project in PHP and we have Sonar performing an analysis of the project (the tasks are executed using Maven). Pdepend runs properly (although it needs a long time and uses 12GB of RAM and 400MB of disk), but phpmd dies after 7 minutes. This was working for us until a month or so, when we refactored some classes and merged some branches.

The error is: 
> [DEBUG] [10:59:28.538] Release semaphore on project : org.sonar.api.resources.Project@19b45d3d[id=1,key=Group_name:name,qualifier=TRK], with key batch-Group_name:name
> [DEBUG] [10:59:28.935] To prevent a memory leak, the JDBC Driver [org.postgresql.Driver] has been forcibly deregistered
> [DEBUG] [10:59:30.270] Delete temporary directory: /tmp/sonar-batch32276477681916127518875165597860515
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 16:38.387s
> [INFO] Finished at: Wed Aug 07 10:59:30 CEST 2013
> [INFO] Final Memory: 23M/762M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.0:sonar (default-cli) on project name: Can not execute Sonar: PHPMD execution failed with returned code '137'. Please check the documentation of PHPMD to know more about this failure. -> [Help 1]

If I execute in a terminal the same command that Sonar is running, I get no error or any output, and the xml report file is empty.
I have not found any option in phpmd to have verbose messages and find out how to solve the issue (e.g. --debug). 

Some guidance will be really appreciated.
Thank you

**Comment by ravage84** [comment]
It seems to be a resource related problem on the executing machine.
If one of you is interested in tweaking the memory consumption of either phpmd or pdepend, you are very welcome.
