### ISSUE TITLE
Avoid unused private fields with constructor property promotion in PHP 8.0

### ISSUE THREAD

**Issue by cnizzardini** [phpmd/phpmd#993]
- PHPMD version: 2.13.0
- PHP Version: 8.0.24
- Installation type: composer
- Operating System / Distribution & Version: Ubuntu 22

### Current Behavior

```
FILE: /var/www/personal/cakephp-swagger-bake/src/Lib/Factory/SwaggerFactory.php
-------------------------------------------------------------------------------
 25 | VIOLATION | Avoid unused private fields such as '$config'.
 30 | VIOLATION | Avoid unused private fields such as '$routeScanner'.
```

### Expected Behavior

In PHP 8.1 this is not an issue, only in PHP 8.0 and I have not tested in PHP 8.2. I see there is an issue and PR for this here which has been resolved https://github.com/phpmd/phpmd/issues/884 yet I am having this issue.

### Steps To Reproduce:

See this: https://github.com/cnizzardini/cakephp-swagger-bake/blob/master/src/Lib/SwaggerFactory.php

## Checks before submitting
* [ ] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [ ] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [X] I have added every step to reproduce the bug.
* [X] If possible I added relevant code examples.
* [X] This issue is about 1 bug and nothing more.
* [X] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by dimitriBouteille** [comment]
Same error with PHP 8.1 with following code :( 

- PHPMD version: 2.13.0
- pdepend/pdepend : 2.12.1
- PHP Version: 8.1
- Installation type: composer

```php
public function __construct(
    protected \Magento\Framework\App\Helper\Context $context,
    protected \Magento\Framework\Locale\ResolverInterface $localeResolver,
    protected \Magento\Framework\Stdlib\DateTime\TimezoneInterface $timezone,
    protected \Magento\Framework\Stdlib\Cookie\CookieMetadataFactory $cookieMetadataFactory,
    protected \Magento\Framework\Stdlib\CookieManagerInterface $cookieManager,
    protected \Magento\Sales\Api\Data\OrderInterfaceFactory $orderFactory,
    protected \Reflet\Preorder\Helper\Config $preorderConfig
) {
    parent::__construct($context);
}
```

**Comment by tvbeek** [comment]
@cnizzardini can you check your PHP Depend  version? ( composer info pdepend/pdepend )

I did test it with PHPMD 2.13.0 and pdepend 2.14.0 but for me it didn't result in an error.

`docker run --rm -v $(pwd):$(pwd) -w $(pwd) php:8.0 vendor/bin/phpmd SwaggerFactory.php text cleancode,codesize,controversial,design,naming,unusedcode`



@dimitriBouteille you only show a part of the class. But with the latest versions I can't reproduce it. Can you give more information?

**Comment by kylekatarnls** [comment]
I confirm it does not happen with latest versions.
